/**
 * 引擎构建脚本：把 service/src/** 打成可交付的 service/*.mjs，并同步 plugin.json 的 sha256。
 *
 *   node scripts/build-engine.mjs            # 校验：磁盘上的产物是否与 plugin.json 声明一致
 *   node scripts/build-engine.mjs --write    # 重新构建 + 回填 sha256 / runtime.version
 *
 * 为什么产物放在 service/ 而不是 dist/：
 *   vite build 会清空 dist/，而宿主 install() 的 payload 必须与 plugin.json 声明的
 *   destination + sha256 逐字节一致；把产物放在 vite 管辖之外才能稳定复现。
 *   构建顺序固定为：node scripts/build-engine.mjs && npm run build
 *
 * 产物布局（相对插件根）：
 *   service/main.mjs                     ← service/src/http-server.mjs
 *   service/drivers/<id>-driver.mjs      ← service/src/drivers/<id>-driver.mjs
 * 驱动与 registry 的一致性由本脚本双向校验（多一个或少一个文件都报错）。
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const SERVICE_SRC = join(ROOT, "service", "src");
const SERVICE_OUT = join(ROOT, "service");
const MANIFEST_PATH = join(ROOT, "plugin.json");
const SERVICE_ID = "dbx-engine";
/** 引擎是纯 JS，所有平台共用同一份字节；这里如实声明全部受支持平台。 */
const PLATFORMS = ["darwin-arm64", "darwin-x64", "linux-arm64", "linux-x64", "win32-x64"];

const write = process.argv.includes("--write");

function sha256(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

async function buildBundles(esbuild) {
  const outputs = [];
  const banner = "// dbx-pro engine bundle — generated by scripts/build-engine.mjs; DO NOT EDIT.\n";

  const main = await esbuild.build({
    entryPoints: [join(SERVICE_SRC, "http-server.mjs")],
    outfile: join(SERVICE_OUT, "main.mjs"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    packages: "external",
    sourcemap: false,
    minify: false,
    legalComments: "none",
    banner: { js: banner },
    logLevel: "warning",
  });
  if (main.errors.length > 0) throw new Error(`engine bundle failed: ${JSON.stringify(main.errors)}`);

  const driverDir = join(SERVICE_SRC, "drivers");
  const driverSources = readdirSync(driverDir).filter((name) => name.endsWith("-driver.mjs"));
  mkdirSync(join(SERVICE_OUT, "drivers"), { recursive: true });
  for (const name of driverSources) {
    const built = await esbuild.build({
      entryPoints: [join(driverDir, name)],
      outfile: join(SERVICE_OUT, "drivers", name),
      bundle: true,
      format: "esm",
      platform: "node",
      target: "node22",
      packages: "external",
      sourcemap: false,
      minify: false,
      legalComments: "none",
      banner: { js: banner },
      logLevel: "warning",
    });
    if (built.errors.length > 0) throw new Error(`driver bundle failed (${name}): ${JSON.stringify(built.errors)}`);
    outputs.push(`service/drivers/${name}`);
  }
  outputs.unshift("service/main.mjs");
  return outputs;
}

/** 双向校验：registry 声明的驱动 ↔ service/src/drivers/*.mjs 文件。 */
async function assertDriverConsistency() {
  const registry = await import(new URL(`file://${join(SERVICE_SRC, "driver-registry.mjs")}`).href);
  const registered = new Set(registry.DRIVER_TABLE.map((entry) => entry.id));
  for (const entry of registry.DRIVER_TABLE) {
    for (const alias of entry.aliases ?? []) registered.add(alias);
  }
  const files = readdirSync(join(SERVICE_SRC, "drivers"))
    .filter((name) => name.endsWith("-driver.mjs"))
    .map((name) => name.replace("-driver.mjs", ""));
  const orphans = files.filter((id) => !registered.has(id));
  const missing = [...registered].filter((id) => registry.DRIVER_TABLE.some((entry) => entry.id === id) && !files.includes(id));
  if (orphans.length > 0) throw new Error(`service/src/drivers 存在未注册的驱动：${orphans.join(", ")}`);
  if (missing.length > 0) throw new Error(`registry 声明了驱动但没有实现文件：${missing.join(", ")}`);
  return { registered: [...registered], files };
}

function readManifest() {
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}

function serviceOf(manifest) {
  const services = manifest.providers?.services ?? [];
  const service = services.find((entry) => entry.id === SERVICE_ID);
  if (!service) throw new Error(`plugin.json 缺少 providers.services[${SERVICE_ID}]`);
  return service;
}

function artifactsOf(manifest) {
  const service = serviceOf(manifest);
  const platform = service.runtime.platforms[PLATFORMS[0]];
  if (!platform) throw new Error(`plugin.json 缺少 runtime.platforms.${PLATFORMS[0]}`);
  return platform.artifacts;
}

async function main() {
  const { createRequire } = await import("node:module");
  const require = createRequire(import.meta.url);
  let esbuild;
  try {
    esbuild = require("esbuild");
  } catch {
    throw new Error("缺少 esbuild：请在插件目录安装 devDependency 后重试");
  }

  const consistency = await assertDriverConsistency();
  console.log(`[build-engine] drivers: ${consistency.files.join(", ")}`);

  if (write) {
    const outputs = await buildBundles(esbuild);
    const manifest = readManifest();
    const artifacts = artifactsOf(manifest);
    const declared = new Map(artifacts.map((artifact) => [artifact.destination, artifact]));
    if (declared.size !== outputs.length) {
      throw new Error(
        `plugin.json 声明的产物数（${declared.size}）与构建结果（${outputs.length}）不一致，请先补齐声明`,
      );
    }
    const engineVersion = await readEngineVersion();
    const summary = [];
    for (const destination of outputs) {
      const artifact = declared.get(destination);
      if (!artifact) throw new Error(`构建产物未在 plugin.json 中声明：${destination}`);
      const buffer = readFileSync(join(ROOT, destination));
      artifact.sha256 = sha256(buffer);
      summary.push({ destination, bytes: statSync(join(ROOT, destination)).size, sha256: artifact.sha256 });
    }
    const previousVersion = serviceOf(manifest).runtime.version;
    const versionChanged = previousVersion !== engineVersion;
    for (const platform of Object.values(serviceOf(manifest).runtime.platforms)) {
      for (const artifact of platform.artifacts) {
        const updated = declared.get(artifact.destination);
        if (updated) artifact.sha256 = updated.sha256;
      }
    }
    serviceOf(manifest).runtime.version = engineVersion;
    writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
    console.log(JSON.stringify({ mode: "write", engineVersion, versionChanged, artifacts: summary }, null, 2));
    if (!versionChanged) {
      console.log(
        "[build-engine] 提醒：runtime.version 未变化。产物内容变化必须提升 ENGINE_VERSION，否则宿主不会重装已有版本。",
      );
    }
    return;
  }

  const manifest = readManifest();
  const artifacts = artifactsOf(manifest);
  const summary = [];
  let mismatch = 0;
  for (const artifact of artifacts) {
    const path = join(ROOT, artifact.destination);
    let buffer;
    try {
      buffer = readFileSync(path);
    } catch {
      summary.push({ destination: artifact.destination, status: "MISSING" });
      mismatch += 1;
      continue;
    }
    const actual = sha256(buffer);
    summary.push({
      destination: artifact.destination,
      bytes: buffer.length,
      sha256: actual,
      status: actual === artifact.sha256 ? "ok" : "SHA256_MISMATCH",
    });
    if (actual !== artifact.sha256) mismatch += 1;
  }
  console.log(JSON.stringify({ mode: "check", artifacts: summary }, null, 2));
  if (mismatch > 0) {
    console.error(`[build-engine] 产物与 plugin.json 声明不一致（${mismatch} 项），请运行 node scripts/build-engine.mjs --write`);
    process.exit(1);
  }
}

async function readEngineVersion() {
  const protocol = await import(new URL(`file://${join(SERVICE_SRC, "engine", "protocol.mjs")}`).href);
  return protocol.ENGINE_VERSION;
}

main().catch((error) => {
  console.error(`[build-engine] ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});
