/**
 * 引擎构建脚本：bundle server/main.mjs + 拉取 dbx-mcp 二进制 + 回填 plugin.json sha256。
 *
 *   node scripts/build-engine.mjs            # 校验：磁盘产物 ↔ plugin.json 声明
 *   node scripts/build-engine.mjs --write    # 构建 + 下载二进制 + 回填 sha256 / runtime.version
 *
 * 产物布局：
 *   server/main.mjs                              ← server/src/http-server.mjs (ES bundle)
 *   server/bin/dbx-mcp-darwin-arm64              ← fork release 预编译
 *   server/bin/dbx-mcp-darwin-x64                ← fork release 预编译
 *   server/bin/dbx-mcp-win-x64.exe               ← fork release 预编译
 *
 * dbx-mcp 二进制从 fork repo https://github.com/maomaochong-ai/dbx release 下载，
 * 硬编码 tag + asset 名，不走 npm / 不依赖旧项目路径。
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, mkdirSync, statSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const SERVER_SRC = join(ROOT, "server", "src");
const SERVER_OUT = join(ROOT, "server");
const BIN_DIR = join(SERVER_OUT, "bin");
const MANIFEST_PATH = join(ROOT, "plugin.json");
const RUNTIME_LOCK_PATH = join(ROOT, "runtime-lock.json");
const SERVICE_ID = "dbx-engine";

// === dbx-mcp 二进制来源（硬编码 fork release） ===
const DBX_FORK_REPO = "maomaochong-ai/dbx";
const DBX_RELEASE_TAG = "dbx-mcp-astravia-v0.4.106";
const DBX_RELEASE_BASE = `https://github.com/${DBX_FORK_REPO}/releases/download/${DBX_RELEASE_TAG}`;

/** 平台 → fork release asset 名 + 本地目标名 + 本地权限（executable） */
const DBX_BINARIES = [
  { platform: "darwin-arm64", asset: "dbx-mcp-0.4.106-astravia-darwin-arm64",   dest: "dbx-mcp-darwin-arm64",   exec: true },
  { platform: "darwin-x64",   asset: "dbx-mcp-0.4.106-astravia-darwin-x64",     dest: "dbx-mcp-darwin-x64",     exec: true },
  { platform: "win32-x64",    asset: "dbx-mcp-0.4.106-astravia-win-x64.exe",    dest: "dbx-mcp-win-x64.exe",    exec: false },
];

/** 当前支持的运行平台（Linux 暂不支持 dbx-mcp binary，宿主 install 时跳过） */
const PLATFORMS = ["darwin-arm64", "darwin-x64", "win32-x64"];

const write = process.argv.includes("--write");

function sha256(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

/**
 * 确保 dbx-mcp 二进制存在于 server/bin/。
 * 已存在 + 大小 > 1MB → 直接跳过（网络 fetch 可能不可用）。
 * 不存在才从 fork release 下载（fetch 失败则报错）。
 */
async function ensureDbxBinary(platform, asset, dest, exec) {
  const destPath = join(BIN_DIR, dest);
  mkdirSync(BIN_DIR, { recursive: true });

  // 已存在 + 大小合理 → 直接跳过
  if (existsSync(destPath) && statSync(destPath).size > 1_000_000) {
    const sizeMB = (statSync(destPath).size / 1_048_576).toFixed(1);
    console.log(`  [local] ${platform} ${dest} (${sizeMB}MB, sha256=${sha256(readFileSync(destPath)).slice(0,16)}...)`);
    return destPath;
  }

  // 不存在才下载
  const url = `${DBX_RELEASE_BASE}/${asset}`;
  console.log(`  [fetch] ${platform} ${asset} ← ${url}`);
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`download failed ${asset}: ${resp.status} (local fallback not available)`);
  const buf = Buffer.from(await resp.arrayBuffer());
  writeFileSync(destPath, buf);
  if (exec) chmodSync(destPath, 0o755);
  const sizeMB = (buf.length / 1_048_576).toFixed(1);
  console.log(`  [ok] ${platform} ${dest} (${sizeMB}MB, sha256=${sha256(buf).slice(0,16)}...)`);
  return destPath;
}

/** bundle main.mjs（自包含：pg/mysql2/mssql 写驱动一并打包，node 内置模块外置）。 */
async function buildMainBundle(esbuild) {
  // 说明：这是【生成产物】，由 scripts/build-engine.mjs 从 server/src 打包；不要手改。
  // banner 用纯 ASCII，避免破折号在某些编辑器里被误判为乱码。
  const banner = "// dbx-pro engine bundle - generated by scripts/build-engine.mjs; DO NOT EDIT.\nimport { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);\n";
  const result = await esbuild.build({
    entryPoints: [join(SERVER_SRC, "http-server.mjs")],
    outfile: join(SERVER_OUT, "main.mjs"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    // pg/mysql2/mssql 必须打进 bridge：宿主 runtime 目录只 stage 本产物与 dbx-mcp 二进制。
    // 仅外置无法/无需打包的项：pg 的可选原生绑定。
    external: ["pg-native"],
    sourcemap: false,
    // 不压缩：产物保持可读、可排查（这是用户明确要求），代价是体积约 4MB。
    minify: false,
    legalComments: "none",
    banner: { js: banner },
    logLevel: "warning",
  });
  if (result.errors.length > 0) throw new Error(`main bundle failed: ${JSON.stringify(result.errors)}`);
  return "server/main.mjs";
}

function readManifest() {
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}

function serviceOf(manifest) {
  const services = manifest.providers?.services ?? [];
  const service = services.find((entry) => entry.id === SERVICE_ID);
  if (!service) throw new Error(`plugin.json 缺少 providers.services[${SERVICE_ID}]`);
  return service;
}

/** 平台 → artifacts 查找（destination 精确匹配）。 */
function findArtifact(platformArtifacts, destination) {
  return platformArtifacts.find((a) => a.destination === destination);
}

async function main() {
  const { createRequire } = await import("node:module");
  const require = createRequire(import.meta.url);
  let esbuild;
  try { esbuild = require("esbuild"); }
  catch { throw new Error("缺少 esbuild：请在插件目录安装 devDependency 后重试"); }

  if (write) {
    // 1. bundle main.mjs
    const outputs = [];
    const mainDest = await buildMainBundle(esbuild);
    outputs.push(mainDest);
    console.log(`[build] main bundle → ${mainDest}`);

    // 2. download dbx-mcp binaries（并行）
    console.log(`[download] fetching dbx-mcp binaries from fork release ${DBX_RELEASE_TAG}...`);
    await Promise.all(DBX_BINARIES.map(b => ensureDbxBinary(b.platform, b.asset, b.dest, b.exec)));
    for (const b of DBX_BINARIES) outputs.push(`server/bin/${b.dest}`);

    // 3. 回填 plugin.json
    const manifest = readManifest();
    const svc = serviceOf(manifest);
    const mainSha = sha256(readFileSync(join(ROOT, mainDest)));
    const binaryShas = Object.fromEntries(
      DBX_BINARIES.map(b => [`server/bin/${b.dest}`, sha256(readFileSync(join(ROOT, "server", "bin", b.dest)))])
    );

    // 所有平台共享 main.mjs 的 sha256（JS bundle 跨平台相同）
    for (const [platformKey, platformCfg] of Object.entries(svc.runtime.platforms || {})) {
      const mainArtifact = findArtifact(platformCfg.artifacts, "server/main.mjs");
      if (mainArtifact) mainArtifact.sha256 = mainSha;
      // 该平台的 dbx-mcp 二进制
      const binEntry = DBX_BINARIES.find(b => b.platform === platformKey);
      if (binEntry) {
        const binArtifact = findArtifact(platformCfg.artifacts, `server/bin/${binEntry.dest}`);
        if (binArtifact) binArtifact.sha256 = binaryShas[`server/bin/${binEntry.dest}`];
      }
    }

    // runtime.version bump（如果 main 内容有变化）
    const protocol = await import(new URL(`file://${join(SERVER_SRC, "engine", "protocol.mjs")}`).href);
    const prevVersion = svc.runtime.version;
    svc.runtime.version = protocol.ENGINE_VERSION;

    writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);

    // 4. 同步 runtime-lock.json（runtime.ts 的 bin 读取/网络兜底清单）。
    // 必须与 plugin.json platforms.artifacts 同源：曾因两份清单版本漂移
    // （plugin.json=0.4.106 / runtime-lock=0.4.61）导致包内 bin SHA 校验失败、
    // 回退下载旧二进制，宿主 install 报 "Service runtime artifact SHA-256 mismatch"。
    const mcpVersion = DBX_RELEASE_TAG.match(/v([\d.]+)$/)?.[1];
    if (!mcpVersion) throw new Error(`无法从 release tag 解析引擎版本：${DBX_RELEASE_TAG}`);
    const runtimeLock = existsSync(RUNTIME_LOCK_PATH)
      ? JSON.parse(readFileSync(RUNTIME_LOCK_PATH, "utf8"))
      : {};
    runtimeLock.version = mcpVersion;
    runtimeLock.platforms = Object.fromEntries(
      DBX_BINARIES.map((b) => [
        b.platform,
        [
          {
            destination: `server/bin/${b.dest}`,
            url: `${DBX_RELEASE_BASE}/${b.asset}`,
            sha256: binaryShas[`server/bin/${b.dest}`],
          },
        ],
      ]),
    );
    writeFileSync(RUNTIME_LOCK_PATH, `${JSON.stringify(runtimeLock, null, 2)}\n`);
    console.log(`[build] runtime-lock.json 已同步（dbx-mcp ${mcpVersion}）`);

    const summary = [
      { destination: mainDest, sha256: mainSha.slice(0, 32) + "...", bytes: statSync(join(ROOT, mainDest)).size },
      ...DBX_BINARIES.map(b => {
        const p = join(ROOT, "server", "bin", b.dest);
        return { destination: `server/bin/${b.dest}`, sha256: binaryShas[`server/bin/${b.dest}`].slice(0, 32) + "...", bytes: statSync(p).size };
      }),
    ];
    console.log(JSON.stringify({ mode: "write", runtimeVersion: `${prevVersion} → ${protocol.ENGINE_VERSION}`, outputs: summary }, null, 2));
    return;
  }

  // === 校验模式：检查 plugin.json 声明的产物是否存在 + sha256 一致 ===
  const manifest = readManifest();
  const svc = serviceOf(manifest);
  // 选一个平台检查 artifacts（main.mjs 跨平台同）
  const firstPlatform = Object.values(svc.runtime.platforms || {})[0];
  if (!firstPlatform) throw new Error("plugin.json 缺少 runtime.platforms");

  const summary = [];
  let mismatch = 0;

  // 1. main.mjs
  const mainPath = join(ROOT, "server", "main.mjs");
  if (!existsSync(mainPath)) {
    summary.push({ destination: "server/main.mjs", status: "MISSING" });
    mismatch++;
  } else {
    const actual = sha256(readFileSync(mainPath));
    const declared = findArtifact(firstPlatform.artifacts, "server/main.mjs")?.sha256;
    summary.push({
      destination: "server/main.mjs",
      bytes: statSync(mainPath).size,
      sha256: actual.slice(0, 32) + "...",
      status: actual === declared ? "ok" : "SHA256_MISMATCH",
    });
    if (actual !== declared) mismatch++;
  }

  // 2. dbx-mcp 二进制（只检查当前平台对应的那份）
  const platform = PLATFORMS.find(p => {
    const pf = process.platform;
    const arch = process.arch;
    if (pf === "darwin" && arch === "arm64") return p === "darwin-arm64";
    if (pf === "darwin" && arch === "x64") return p === "darwin-x64";
    if (pf === "win32" && arch === "x64") return p === "win32-x64";
    return false;
  });
  if (platform) {
    const binEntry = DBX_BINARIES.find(b => b.platform === platform);
    const binPath = join(ROOT, "server", "bin", binEntry.dest);
    // 用当前平台的 artifacts 查声明，不能用 firstPlatform：每个平台只声明自己的二进制，
    // 拿 arm64 那份去查 darwin-x64 的产物永远是 undefined（假阳性的 SHA256_MISMATCH）。
    const declared = findArtifact(svc.runtime.platforms[platform].artifacts, `server/bin/${binEntry.dest}`)?.sha256;
    if (!existsSync(binPath)) {
      summary.push({ destination: `server/bin/${binEntry.dest}`, status: "MISSING" });
      mismatch++;
    } else {
      const actual = sha256(readFileSync(binPath));
      summary.push({
        destination: `server/bin/${binEntry.dest}`,
        bytes: statSync(binPath).size,
        sha256: actual.slice(0, 32) + "...",
        status: actual === declared ? "ok" : "SHA256_MISMATCH",
      });
      if (actual !== declared) mismatch++;
    }
  }

  console.log(JSON.stringify({ mode: "check", platform, artifacts: summary }, null, 2));
  if (mismatch > 0) {
    console.error(`[build-engine] ${mismatch} 项与 plugin.json 不一致，请运行 node scripts/build-engine.mjs --write`);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error(`[build-engine] ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});
