// dbx-pro engine bundle — generated by scripts/build-engine.mjs; DO NOT EDIT.


// service/src/drivers/sqlite-driver.mjs
import { closeSync, existsSync, openSync, readSync, statSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";

// service/src/engine/protocol.mjs
var MAX_BODY_BYTES = 8 * 1024 * 1024;
var DEFAULT_ROW_LIMIT = 500;
var MAX_ROW_LIMIT = 5e3;
var STATUS_BY_CODE = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PAYLOAD_TOO_LARGE: 413,
  WRITE_BLOCKED: 403,
  DDL_BLOCKED: 403,
  CONFIRM_MISMATCH: 403,
  PROD_WRITE_BLOCKED: 403,
  DRIVER_UNSUPPORTED: 501,
  DRIVER_ERROR: 502,
  CONNECTION_ERROR: 502,
  TIMEOUT: 504,
  INTERNAL: 500
});
var EngineError = class extends Error {
  constructor(code, message, detail) {
    super(message);
    this.name = "EngineError";
    this.code = code;
    this.detail = detail;
    this.engineError = true;
  }
};
function engineError(code, message, detail) {
  return new EngineError(code, message, detail);
}
function isEngineError(value) {
  return Boolean(value) && typeof value === "object" && value.engineError === true && typeof value.code === "string";
}

// service/src/engine/query-guard.mjs
var READ_LEADERS = /* @__PURE__ */ new Set(["SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "USE", "VALUES"]);
var DDL_KEYWORDS = ["CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME"];
var DDL_LEADERS = new Set(DDL_KEYWORDS);
var DDL_KEYWORD_RE = new RegExp(`\\b(${DDL_KEYWORDS.join("|")})\\b`);
var WRITE_KEYWORDS = [
  "INSERT",
  "UPDATE",
  "DELETE",
  "REPLACE",
  "MERGE",
  "UPSERT",
  "TRUNCATE",
  "CREATE",
  "ALTER",
  "DROP",
  "GRANT",
  "REVOKE",
  "COMMENT",
  "CALL",
  "EXEC",
  "EXECUTE",
  "DO",
  "VACUUM",
  "REINDEX",
  "COPY",
  "LOAD",
  "LOCK",
  "ATTACH",
  "DETACH",
  "RENAME",
  "ANALYZE",
  "SET"
];
var WRITE_KEYWORD_RE = new RegExp(`\\b(${WRITE_KEYWORDS.join("|")})\\b`);
var QUOTE_CLOSERS = { "'": "'", '"': '"', "`": "`", "[": "]" };
function scanSql(sql, { onCode, onLiteral }) {
  const text = String(sql ?? "");
  const length = text.length;
  let index = 0;
  let code = "";
  const flushCode = () => {
    if (code.length > 0) {
      onCode(code);
      code = "";
    }
  };
  while (index < length) {
    const char = text[index];
    const closer = QUOTE_CLOSERS[char];
    if (closer !== void 0) {
      flushCode();
      let literal = char;
      index += 1;
      while (index < length) {
        const inner = text[index];
        literal += inner;
        if (inner === closer) {
          if (closer !== "]" && text[index + 1] === closer) {
            literal += text[index + 1];
            index += 2;
            continue;
          }
          index += 1;
          break;
        }
        index += 1;
      }
      onLiteral(literal);
      continue;
    }
    if (char === "-" && text[index + 1] === "-") {
      while (index < length && text[index] !== "\n" && text[index] !== "\r") index += 1;
      code += " ";
      continue;
    }
    if (char === "/" && text[index + 1] === "*") {
      index += 2;
      while (index < length && !(text[index] === "*" && text[index + 1] === "/")) index += 1;
      index = Math.min(index + 2, length);
      code += " ";
      continue;
    }
    code += char;
    index += 1;
  }
  flushCode();
}
function stripSqlComments(sql) {
  let stripped = "";
  scanSql(sql, {
    onCode: (chunk) => {
      stripped += chunk;
    },
    onLiteral: (literal) => {
      stripped += literal;
    }
  });
  return stripped.trim();
}
function keywords(sql) {
  return stripSqlComments(sql).toUpperCase().split(/[^A-Z0-9_$]+/).filter((token) => token.length > 0);
}
function isWriteStatement(sql) {
  const cleaned = stripSqlComments(sql);
  if (cleaned.length === 0) return false;
  const tokens = keywords(sql);
  if (tokens.length === 0) return false;
  const [first, second] = tokens;
  if (first === "EXPLAIN" && second === "ANALYZE") {
    return isWriteStatement(cleaned.slice(cleaned.toUpperCase().indexOf("ANALYZE") + "ANALYZE".length));
  }
  if (first === "WITH") {
    return WRITE_KEYWORD_RE.test(cleaned.toUpperCase());
  }
  if (READ_LEADERS.has(first)) return false;
  return true;
}

// service/src/drivers/sqlite-driver.mjs
var descriptor = {
  id: "sqlite",
  label: "SQLite",
  family: "sqlite",
  tier: "first-class",
  defaultPort: 0,
  fileBased: true
};
function quoteIdent(identifier) {
  return `"${String(identifier).replaceAll('"', '""')}"`;
}
var SQLITE_MAGIC = Buffer.from("SQLite format 3\0", "latin1");
function assertOpenableSqliteFile(file) {
  let stats;
  try {
    stats = statSync(file);
  } catch {
    throw engineError("CONNECTION_ERROR", `\u65E0\u6CD5\u8BFB\u53D6\u6570\u636E\u5E93\u6587\u4EF6\uFF1A${file}`, { file });
  }
  if (!stats.isFile()) {
    throw engineError("CONNECTION_ERROR", `\u4E0D\u662F\u666E\u901A\u6587\u4EF6\uFF1A${file}`, { file });
  }
  if (stats.size === 0) return;
  let descriptor2;
  let header;
  try {
    descriptor2 = openSync(file, "r");
    header = Buffer.alloc(16);
    const read = readSync(descriptor2, header, 0, 16, 0);
    header = header.subarray(0, read);
  } catch {
    throw engineError("CONNECTION_ERROR", `\u65E0\u6CD5\u8BFB\u53D6\u6570\u636E\u5E93\u6587\u4EF6\uFF1A${file}`, { file });
  } finally {
    if (descriptor2 !== void 0) closeSync(descriptor2);
  }
  if (header.length !== SQLITE_MAGIC.length || !header.equals(SQLITE_MAGIC)) {
    throw engineError("CONNECTION_ERROR", `\u4E0D\u662F\u6709\u6548\u7684 SQLite \u6570\u636E\u5E93\u6587\u4EF6\uFF1A${file}`, { file });
  }
}
function sqliteFilePath(spec) {
  const candidate = [spec.file, spec.database, spec.host].find(
    (value) => typeof value === "string" && value.trim().length > 0
  );
  if (!candidate) {
    throw engineError("BAD_REQUEST", "SQLite \u8FDE\u63A5\u7F3A\u5C11\u6570\u636E\u5E93\u6587\u4EF6\u8DEF\u5F84\uFF08file/database\uFF09");
  }
  return candidate.trim();
}
function normalizeValue(value) {
  if (typeof value === "bigint") {
    const max = BigInt(Number.MAX_SAFE_INTEGER);
    const min = BigInt(Number.MIN_SAFE_INTEGER);
    return value <= max && value >= min ? Number(value) : value.toString();
  }
  if (value instanceof Uint8Array) {
    return { __type: "blob", bytes: value.byteLength, base64: Buffer.from(value).toString("base64") };
  }
  return value;
}
function normalizeRow(row) {
  const output = {};
  for (const [key, value] of Object.entries(row)) output[key] = normalizeValue(value);
  return output;
}
function clampRowLimit(rowLimit) {
  const value = Number.isFinite(rowLimit) ? Math.trunc(rowLimit) : DEFAULT_ROW_LIMIT;
  return Math.min(Math.max(value, 1), MAX_ROW_LIMIT);
}
function runStatement(db, sql, { rowLimit, shouldAbort }) {
  if (shouldAbort?.()) throw engineError("TIMEOUT", "\u67E5\u8BE2\u8D85\u65F6\uFF08\u5728\u8BED\u53E5\u4E4B\u95F4\u4E2D\u65AD\uFF09");
  const statement = db.prepare(sql);
  let declared = null;
  try {
    declared = statement.columns();
  } catch {
    declared = null;
  }
  const readsRows = declared ? declared.length > 0 : !isWriteStatement(sql);
  if (!readsRows) {
    const result = statement.run();
    return {
      sql,
      kind: "write",
      columns: [],
      rows: [],
      row_count: 0,
      affected_rows: Number(result.changes ?? 0),
      last_insert_rowid: typeof result.lastInsertRowid === "bigint" ? Number(result.lastInsertRowid) : result.lastInsertRowid,
      truncated: false
    };
  }
  statement.setReadBigInts(true);
  const rows = [];
  let truncated = false;
  for (const row of statement.iterate()) {
    if (shouldAbort?.()) throw engineError("TIMEOUT", "\u67E5\u8BE2\u8D85\u65F6\uFF08\u5728\u8BED\u53E5\u4E4B\u95F4\u4E2D\u65AD\uFF09");
    if (rows.length >= rowLimit) {
      truncated = true;
      break;
    }
    rows.push(normalizeRow(row));
  }
  const columns = rows.length > 0 ? Object.keys(rows[0]) : (declared ?? []).map((column) => column.name);
  return { sql, kind: "read", columns, rows, row_count: rows.length, affected_rows: 0, truncated };
}
function createDriver() {
  return {
    descriptor,
    /** 打开一个连接句柄。生命周期由 ConnectionPool 管理。 */
    acquire(spec) {
      const file = sqliteFilePath(spec);
      if (file !== ":memory:" && !existsSync(file)) {
        throw engineError("CONNECTION_ERROR", `\u6570\u636E\u5E93\u6587\u4EF6\u4E0D\u5B58\u5728\uFF1A${file}`, { file });
      }
      if (file !== ":memory:") assertOpenableSqliteFile(file);
      let db;
      try {
        db = spec.readOnly === true ? new DatabaseSync(file, { readOnly: true }) : new DatabaseSync(file);
      } catch (error) {
        if (isEngineError(error)) throw error;
        throw engineError("CONNECTION_ERROR", error instanceof Error ? error.message : String(error), { file });
      }
      return {
        file,
        native: db,
        test() {
          const started = Date.now();
          const row = db.prepare("select sqlite_version() as version").get();
          return {
            serverVersion: String(row?.version ?? "unknown"),
            database: file,
            latencyMs: Date.now() - started,
            readOnly: spec.readOnly === true
          };
        },
        catalog() {
          const namespaces = db.prepare("PRAGMA database_list").all().map((row) => ({ name: String(row.name), file: row.file ? String(row.file) : null, default: row.name === "main" }));
          const objects = [];
          for (const namespace of namespaces) {
            const sql = `select name, type from ${quoteIdent(namespace.name)}.sqlite_master where type in ('table','view') order by name`;
            for (const row of db.prepare(sql).all()) {
              const name = String(row.name);
              objects.push({
                schema: namespace.name,
                name,
                kind: String(row.type),
                system: name.startsWith("sqlite_")
              });
            }
          }
          return { namespaces, objects };
        },
        describe({ schema = "main", table } = {}) {
          if (typeof table !== "string" || table.trim().length === 0) {
            throw engineError("BAD_REQUEST", "describe \u9700\u8981 table");
          }
          const name = table.trim();
          const meta = `select sql from ${quoteIdent(schema)}.sqlite_master where name = ?`;
          const metaRow = db.prepare(meta).get(name);
          if (!metaRow) {
            throw engineError("NOT_FOUND", `\u5BF9\u8C61\u4E0D\u5B58\u5728\uFF1A${schema}.${name}`, { schema, table: name });
          }
          let rows = db.prepare(`PRAGMA ${quoteIdent(schema)}.table_info(${quoteIdent(name)})`).all();
          let hidden = false;
          if (rows.length === 0) {
            rows = db.prepare(`PRAGMA ${quoteIdent(schema)}.table_xinfo(${quoteIdent(name)})`).all();
            hidden = true;
          }
          return {
            schema,
            table: name,
            hidden,
            sql: metaRow.sql ? String(metaRow.sql) : null,
            columns: rows.map((row) => ({
              name: String(row.name),
              type: String(row.type ?? ""),
              nullable: Number(row.notnull ?? 0) === 0,
              primaryKey: Number(row.pk ?? 0) > 0,
              defaultValue: row.dflt_value === null || row.dflt_value === void 0 ? null : String(row.dflt_value)
            }))
          };
        },
        /** 执行**单条**语句（多语句由 request-router 切分后逐条调用，便于回报每条的分类与结果）。 */
        query({ sql, rowLimit, shouldAbort } = {}) {
          if (typeof sql !== "string" || sql.trim().length === 0) {
            throw engineError("BAD_REQUEST", "query \u9700\u8981 sql");
          }
          return runStatement(db, sql, { rowLimit: clampRowLimit(rowLimit), shouldAbort });
        },
        close() {
          db.close();
        }
      };
    }
  };
}
export {
  createDriver,
  descriptor
};
