// dbx-pro engine bundle — generated by scripts/build-engine.mjs; DO NOT EDIT.


// service/src/http-server.mjs
import { createHash, timingSafeEqual } from "node:crypto";
import { createServer } from "node:http";

// service/src/engine/protocol.mjs
var ENGINE_VERSION = "0.0.15";
var PROTOCOL_VERSION = 1;
var MAX_BODY_BYTES = 8 * 1024 * 1024;
var DEFAULT_ROW_LIMIT = 500;
var MAX_ROW_LIMIT = 5e3;
var MAX_TIMEOUT_MS = 3e5;
var STATUS_BY_CODE = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PAYLOAD_TOO_LARGE: 413,
  WRITE_BLOCKED: 403,
  DDL_BLOCKED: 403,
  CONFIRM_MISMATCH: 403,
  PROD_WRITE_BLOCKED: 403,
  DRIVER_UNSUPPORTED: 501,
  DRIVER_ERROR: 502,
  CONNECTION_ERROR: 502,
  TIMEOUT: 504,
  INTERNAL: 500
});
function httpStatusForCode(code) {
  return STATUS_BY_CODE[code] ?? 500;
}
var EngineError = class extends Error {
  constructor(code, message, detail) {
    super(message);
    this.name = "EngineError";
    this.code = code;
    this.detail = detail;
    this.engineError = true;
  }
};
function engineError(code, message, detail) {
  return new EngineError(code, message, detail);
}
function isEngineError(value) {
  return Boolean(value) && typeof value === "object" && value.engineError === true && typeof value.code === "string";
}
function normalizeThrown(thrown) {
  if (isEngineError(thrown)) return thrown;
  const message = thrown instanceof Error ? thrown.message : String(thrown);
  const rawCode = thrown && typeof thrown === "object" && typeof thrown.code === "string" ? thrown.code : null;
  if (rawCode === "ERR_SQLITE_ERROR" || rawCode === "ERR_OUT_OF_RANGE") {
    return new EngineError("DRIVER_ERROR", message, { driverCode: rawCode });
  }
  return new EngineError("INTERNAL", message, rawCode ? { driverCode: rawCode } : void 0);
}
function ok(data) {
  return { ok: true, data };
}
function fail(thrown) {
  const error = normalizeThrown(thrown);
  return {
    ok: false,
    error: error.detail === void 0 ? { code: error.code, message: error.message } : { code: error.code, message: error.message, detail: error.detail }
  };
}
function isSafeBigInt(value) {
  return value <= BigInt(Number.MAX_SAFE_INTEGER) && value >= BigInt(Number.MIN_SAFE_INTEGER);
}
function jsonReplacer(_key, value) {
  if (typeof value === "bigint") {
    return isSafeBigInt(value) ? Number(value) : value.toString();
  }
  if (value instanceof Uint8Array) {
    return {
      __type: "blob",
      bytes: value.byteLength,
      base64: Buffer.from(value).toString("base64")
    };
  }
  return value;
}
function stringifyJson(value) {
  return JSON.stringify(value, jsonReplacer);
}

// service/src/engine/dbx-mcp-client.mjs
import { spawn } from "node:child_process";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
var _thisDir = join(fileURLToPath(import.meta.url), "..");
var _serviceDir = _thisDir.endsWith("engine") ? join(_thisDir, "..", "..") : _thisDir;
var BIN_PATH_BY_PLATFORM = {
  "darwin-arm64": join(_serviceDir, "bin", "dbx-mcp-darwin-arm64"),
  "darwin-x64": join(_serviceDir, "bin", "dbx-mcp-darwin-x64"),
  "win32-x64": join(_serviceDir, "bin", "dbx-mcp-win-x64.exe")
};
function resolveDataDir(explicitDir) {
  const dir = explicitDir ?? join(homedir(), ".astravia-dbx-data");
  mkdirSync(dir, { recursive: true });
  return dir;
}
var HANDSHAKE_TIMEOUT_MS = 15e3;
var CALL_TIMEOUT_MS = 6e4;
var SHUTDOWN_GRACE_MS = 2e3;
function detectPlatform() {
  const platform = process.platform;
  const arch = process.arch;
  if (platform === "darwin" && arch === "arm64") return "darwin-arm64";
  if (platform === "darwin" && arch === "x64") return "darwin-x64";
  if (platform === "win32" && arch === "x64") return "win32-x64";
  return null;
}
function resolveBinaryPath() {
  const platform = detectPlatform();
  if (!platform) {
    throw new Error(`dbx-mcp: \u4E0D\u652F\u6301\u7684\u5E73\u53F0 ${process.platform}-${process.arch}\uFF08\u9700\u8981 darwin-arm64 / darwin-x64 / win32-x64\uFF09`);
  }
  return BIN_PATH_BY_PLATFORM[platform];
}
var DbxMcpClient = class {
  constructor(options = {}) {
    this.handshakeTimeoutMs = options.handshakeTimeoutMs ?? HANDSHAKE_TIMEOUT_MS;
    this.callTimeoutMs = options.callTimeoutMs ?? CALL_TIMEOUT_MS;
    this.extraEnv = options.extraEnv ?? {};
    this.dataDir = options.dataDir ?? null;
    this.child = null;
    this.buffer = "";
    this.nextId = 1;
    this.pending = /* @__PURE__ */ new Map();
    this.initialized = null;
  }
  ensureInitialized() {
    if (!this.initialized) {
      this.initialized = this.spawnAndHandshake().catch((err) => {
        this.initialized = null;
        this.reapCurrentChild();
        throw err;
      });
    }
    return this.initialized;
  }
  reapCurrentChild() {
    const child = this.child;
    this.child = null;
    if (!child || child.killed) return;
    child.kill();
    const force = setTimeout(() => {
      if (child && !child.killed) child.kill("SIGKILL");
    }, SHUTDOWN_GRACE_MS);
    if (force.unref) force.unref();
  }
  async callTool(name, args, timeoutMs) {
    await this.ensureInitialized();
    const id = this.nextId++;
    const result = await this.request(
      id,
      "tools/call",
      { name, arguments: args },
      timeoutMs ?? this.callTimeoutMs
    );
    return result;
  }
  async dispose() {
    const child = this.child;
    this.child = null;
    this.initialized = null;
    for (const p of this.pending.values()) p.reject(new Error("dbx-mcp client disposed"));
    this.pending.clear();
    if (!child || child.killed) return;
    const exited = new Promise((resolve) => child.once("exit", () => resolve()));
    child.kill();
    await Promise.race([
      exited,
      new Promise((resolve) => setTimeout(resolve, SHUTDOWN_GRACE_MS))
    ]);
    if (!child.killed) child.kill("SIGKILL");
  }
  spawnAndHandshake() {
    const bin = resolveBinaryPath();
    const dbxDataDir = resolveDataDir(this.dataDir);
    const child = spawn(bin, [], {
      stdio: ["pipe", "pipe", "pipe"],
      env: {
        ...process.env,
        DBX_DATA_DIR: dbxDataDir,
        ...this.extraEnv
      }
    });
    this.child = child;
    const isCurrent = () => this.child === child;
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk) => this.onData(chunk));
    child.stderr.on("data", (chunk) => {
    });
    child.on("exit", (code, signal) => {
      if (!isCurrent()) return;
      const err = new Error(`dbx-mcp exited (code=${code}, signal=${signal})`);
      for (const p of this.pending.values()) p.reject(err);
      this.pending.clear();
      this.child = null;
      this.initialized = null;
    });
    child.on("error", (err) => {
      if (!isCurrent()) return;
      for (const p of this.pending.values()) p.reject(err);
      this.pending.clear();
      this.child = null;
      this.initialized = null;
    });
    return new Promise((resolve, reject) => {
      this.request(
        0,
        "initialize",
        {
          protocolVersion: "2024-11-05",
          capabilities: {},
          clientInfo: { name: "dbx-pro-plugin", version: "0.1.1" }
        },
        this.handshakeTimeoutMs
      ).then(() => {
        if (!isCurrent()) {
          reject(new Error("dbx-mcp client disposed during handshake"));
          return;
        }
        this.sendNotification("notifications/initialized", {});
        resolve();
      }).catch((err) => reject(err));
    });
  }
  request(id, method, params, timeoutMs) {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`dbx-mcp request "${method}" timeout after ${timeoutMs}ms`));
      }, timeoutMs);
      this.pending.set(id, {
        resolve: (result) => {
          clearTimeout(timer);
          resolve(result);
        },
        reject: (err) => {
          clearTimeout(timer);
          reject(err);
        }
      });
      this.sendMessage({ jsonrpc: "2.0", id, method, params });
    });
  }
  sendNotification(method, params) {
    this.sendMessage({ jsonrpc: "2.0", method, params });
  }
  /** 列出 dbx-mcp 暴露的所有 MCP 工具。 */
  async listTools(timeoutMs = 3e4) {
    await this.ensureInitialized();
    const result = await this.request(++this.seq, "tools/list", {}, timeoutMs);
    return result?.tools ?? [];
  }
  sendMessage(message) {
    if (!this.child) throw new Error("dbx-mcp client not started");
    this.child.stdin.write(`${JSON.stringify(message)}
`);
  }
  onData(chunk) {
    this.buffer += chunk;
    let idx = this.buffer.indexOf("\n");
    while (idx !== -1) {
      const line = this.buffer.slice(0, idx).trim();
      this.buffer = this.buffer.slice(idx + 1);
      if (!line) continue;
      this.handleLine(line);
      idx = this.buffer.indexOf("\n");
    }
  }
  handleLine(line) {
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      return;
    }
    if (typeof message.id !== "number") return;
    const p = this.pending.get(message.id);
    if (!p) return;
    this.pending.delete(message.id);
    if (message.error) {
      const msg = typeof message.error === "object" && message.error !== null && "message" in message.error ? String(message.error.message) : "dbx-mcp request error";
      p.reject(new Error(msg));
    } else {
      p.resolve(message.result);
    }
  }
};
var client = null;
function getDbxMcpClient(options) {
  if (!client) client = new DbxMcpClient(options);
  return client;
}
async function disposeDbxMcpClient() {
  if (client) {
    await client.dispose();
    client = null;
  }
}

// service/src/engine/sql-safety.mjs
var READ_LEADERS = /* @__PURE__ */ new Set(["SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "USE", "VALUES"]);
var DDL_KEYWORDS = ["CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME"];
var DDL_LEADERS = new Set(DDL_KEYWORDS);
var DDL_KEYWORD_RE = new RegExp("\\b(?:" + DDL_KEYWORDS.join("|") + ")\\b");
var WRITE_KEYWORDS = [
  "INSERT",
  "UPDATE",
  "DELETE",
  "REPLACE",
  "MERGE",
  "UPSERT",
  "TRUNCATE",
  "CREATE",
  "ALTER",
  "DROP",
  "GRANT",
  "REVOKE",
  "COMMENT",
  "CALL",
  "EXEC",
  "EXECUTE",
  "DO",
  "VACUUM",
  "REINDEX",
  "COPY",
  "LOAD",
  "LOCK",
  "ATTACH",
  "DETACH",
  "RENAME",
  "ANALYZE",
  "SET"
];
var WRITE_KEYWORD_RE = new RegExp("\\b(?:" + WRITE_KEYWORDS.join("|") + ")\\b");
function stripSqlComments(sql) {
  let out = "";
  let i = 0;
  let inLine = false;
  let inBlock = false;
  while (i < sql.length) {
    const ch = sql[i];
    const next = sql[i + 1];
    if (!inLine && !inBlock && ch === "-" && next === "-") {
      inLine = true;
      i += 2;
      continue;
    }
    if (!inLine && !inBlock && ch === "/" && next === "*") {
      inBlock = true;
      i += 2;
      continue;
    }
    if (inLine) {
      if (ch === "\n") inLine = false;
      else {
        i += 1;
        continue;
      }
    }
    if (inBlock) {
      if (ch === "*" && next === "/") {
        inBlock = false;
        i += 2;
        continue;
      }
      i += 1;
      continue;
    }
    out += ch;
    i += 1;
  }
  return out;
}
function firstKeyword(sql) {
  const m = sql.trim().match(/^[a-zA-Z_][a-zA-Z0-9_]*/);
  return m ? m[0].toUpperCase() : "";
}
function isWriteStatement(sql) {
  const cleaned = stripSqlComments(sql).trim();
  if (!cleaned) return false;
  const first = firstKeyword(cleaned);
  if (READ_LEADERS.has(first)) {
    if (first === "EXPLAIN") {
      const rest = cleaned.slice(first.length).trim();
      if (rest.toUpperCase().startsWith("ANALYZE")) {
        const body = rest.slice(7).trim();
        const bodyFirst = firstKeyword(body);
        if (bodyFirst && !READ_LEADERS.has(bodyFirst)) return true;
        return WRITE_KEYWORD_RE.test(body.toUpperCase());
      }
    }
    return false;
  }
  if (first === "WITH") return WRITE_KEYWORD_RE.test(cleaned.toUpperCase());
  return true;
}
function isDdlStatement(sql) {
  const cleaned = stripSqlComments(sql).trim();
  if (!cleaned) return false;
  const first = firstKeyword(cleaned);
  if (DDL_LEADERS.has(first)) return true;
  if (first === "WITH") return DDL_KEYWORD_RE.test(cleaned.toUpperCase());
  return false;
}
function splitStatements(sql) {
  return stripSqlComments(sql).split(";").map((s) => s.trim()).filter((s) => s.length > 0);
}
function classifyQuery(sql) {
  const statements = splitStatements(sql);
  const kinds = statements.map((s) => {
    if (isDdlStatement(s)) return "ddl";
    return isWriteStatement(s) ? "write" : "read";
  });
  let kind = "read";
  for (const k of kinds) {
    if (k === "ddl") kind = "ddl";
    else if (k === "write" && kind !== "ddl") kind = "write";
  }
  const requiresConfirmation = kind !== "read";
  return { kind, kinds, statements, requiresConfirmation };
}

// service/src/engine/direct-driver.mjs
var DRIVER_FAMILY = {
  // PostgreSQL 家族
  postgres: "pg",
  postgresql: "pg",
  redshift: "pg",
  greenplum: "pg",
  cockroachdb: "pg",
  timescaledb: "pg",
  oceanbase: "pg",
  opengauss: "pg",
  gaussdb: "pg",
  highgo: "pg",
  edb: "pg",
  postgis: "pg",
  // MySQL 家族
  mysql: "mysql",
  mariadb: "mysql",
  tidb: "mysql",
  starrocks: "mysql",
  doris: "mysql",
  // SQLite
  sqlite: "sqlite",
  sqlite3: "sqlite",
  // SQL Server
  mssql: "mssql",
  sqlserver: "mssql",
  // ClickHouse
  clickhouse: "clickhouse",
  // DuckDB — 用 node:sqlite 兼容？DuckDB 有自己协议但本地文件模式类似
  duckdb: "sqlite"
};
var DEFAULT_PORT = { pg: 5432, mysql: 3306, mssql: 1433, clickhouse: 9e3 };
async function executeDirect(opts) {
  const { dbType, host, port, username, password, database, sql, ssl, timeoutMs = 3e4 } = opts ?? {};
  if (!dbType) throw mkError("DIRECT_DRIVER_BAD_CONFIG", "Direct driver \u7F3A\u5C11 dbType");
  if (!sql || typeof sql !== "string" || sql.trim().length === 0) throw mkError("BAD_REQUEST", "SQL \u4E0D\u80FD\u4E3A\u7A7A");
  const family = DRIVER_FAMILY[dbType.toLowerCase()];
  if (!family) {
    throw mkError(
      "DIRECT_DRIVER_UNSUPPORTED",
      `Direct driver \u4E0D\u652F\u6301\u7684 dbType: ${dbType}\u3002\u652F\u6301: ${Object.keys(DRIVER_FAMILY).join(", ")}`
    );
  }
  if (family !== "sqlite" && !host) {
    throw mkError("DIRECT_DRIVER_BAD_CONFIG", `Direct driver (${family}) \u7F3A\u5C11 host`);
  }
  if (family === "sqlite" && !database) {
    throw mkError("DIRECT_DRIVER_BAD_CONFIG", "SQLite \u6A21\u5F0F\u7F3A\u5C11 database\uFF08\u6587\u4EF6\u8DEF\u5F84\uFF09");
  }
  const started = Date.now();
  const result = { columns: [], rows: [], rowCount: 0 };
  try {
    switch (family) {
      case "pg":
        return await execPg({ dbType, host, port, username, password, database, sql, ssl, timeoutMs, started });
      case "mysql":
        return await execMy({ dbType, host, port, username, password, database, sql, ssl, timeoutMs, started });
      case "mssql":
        return await execMs({ dbType, host, port, username, password, database, sql, timeoutMs, started });
      case "sqlite":
        return await execSqlite({ dbType, database, sql, started });
      case "clickhouse":
        return await execClickHouse({ dbType, host, port, username, password, database, sql, timeoutMs, started });
    }
  } catch (e) {
    if (e?.code?.startsWith("DIRECT_DRIVER")) throw e;
    const msg = e?.message ?? String(e);
    const err = mkError("DIRECT_DRIVER_ERROR", `Direct driver \u6267\u884C\u5931\u8D25 (${family}): ${msg}`);
    err.cause = e;
    throw err;
  }
}
async function execPg({ dbType, host, port, username, password, database, sql, ssl, timeoutMs, started }) {
  const { default: pg } = await import("pg");
  const pool = new pg.Pool({
    host,
    port: Number(port) || DEFAULT_PORT.pg,
    user: username,
    password,
    database,
    max: 1,
    idleTimeoutMillis: 1e4,
    connectionTimeoutMillis: Math.min(timeoutMs, 1e4),
    ssl: ssl ? { rejectUnauthorized: false } : void 0
  });
  try {
    const client2 = await pool.connect();
    try {
      const r = await client2.query({ text: sql, rowMode: "array" });
      return shapeResult(r.fields, r.rows, r.rowCount, started, dbType, host, port, database, sql);
    } finally {
      client2.release();
    }
  } finally {
    await pool.end();
  }
}
async function execMy({ dbType, host, port, username, password, database, sql, ssl, timeoutMs, started }) {
  const { default: mysql } = await import("mysql2/promise");
  const conn = await mysql.createConnection({
    host,
    port: Number(port) || DEFAULT_PORT.mysql,
    user: username,
    password,
    database,
    ssl: ssl ? { rejectUnauthorized: false } : void 0,
    connectTimeout: Math.min(timeoutMs, 1e4)
  });
  try {
    const [result, fields] = await conn.query({ sql, rowsAsArray: true });
    const columns = fields ? fields.map((f) => f.name) : [];
    let rows = [];
    let rowCount = 0;
    if (Array.isArray(result)) {
      rows = result.map((row) => {
        const obj = {};
        fields.forEach((f, i) => {
          obj[f.name] = row[i];
        });
        return obj;
      });
      rowCount = rows.length;
    } else if (result && typeof result === "object") {
      rowCount = result.affectedRows ?? result.changedRows ?? 0;
    }
    return { columns, rows, rowCount, ...meta(started, dbType, host, port, database, sql) };
  } finally {
    await conn.end();
  }
}
async function execMs({ dbType, host, port, username, password, database, sql, timeoutMs, started }) {
  const sqlSrvModule = await import("mssql");
  const sqlSrv = sqlSrvModule.default ?? sqlSrvModule;
  const pool = await sqlSrv.connect({
    server: host,
    port: Number(port) || DEFAULT_PORT.mssql,
    userName: username,
    password,
    database,
    options: { trustServerCertificate: true, connectTimeout: Math.min(timeoutMs, 1e4) }
  });
  try {
    const r = await pool.request().query(sql);
    const recordsets = r.recordsets || [];
    const first = recordsets[0] || [];
    const columns = r.columns && r.columns[0] ? r.columns[0].map((c) => c.name) : [];
    return {
      columns,
      rows: first,
      rowCount: first.length,
      ...meta(started, dbType, host, port, database, sql)
    };
  } finally {
    await pool.close();
  }
}
async function execSqlite({ dbType, database, sql, started }) {
  const { DatabaseSync } = await import("node:sqlite");
  const db = new DatabaseSync(database);
  try {
    const rows = [];
    let columns = [];
    if (/\b(SELECT|PRAGMA|WITH)\b/i.test(sql)) {
      const stmt = db.prepare(sql);
      for (const row of stmt.all()) {
        if (columns.length === 0) columns = Object.keys(row);
        rows.push({ ...row });
      }
    } else {
      db.exec(sql);
    }
    return { columns, rows, rowCount: rows.length, ...meta(started, dbType, void 0, void 0, database, sql) };
  } finally {
    db.close();
  }
}
async function execClickHouse({ dbType, host, port, username, password, database, sql, timeoutMs, started }) {
  const url = `http://${host}:${port || DEFAULT_PORT.clickhouse}/`;
  const auth = username ? `Basic ${Buffer.from(`${username}:${password ?? ""}`).toString("base64")}` : void 0;
  const headers = { "Content-Type": "text/plain" };
  if (auth) headers.Authorization = auth;
  if (database) headers["X-ClickHouse-Database"] = database;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const query = sql.replace(/;?\s*$/, "") + " FORMAT JSON";
    const res = await fetch(url, {
      method: "POST",
      body: query,
      headers,
      signal: controller.signal
    });
    clearTimeout(timer);
    const text = await res.text();
    if (!res.ok) throw new Error(`ClickHouse HTTP ${res.status}: ${text.slice(0, 200)}`);
    if (!text.trim()) {
      return { columns: [], rows: [], rowCount: 0, ...meta(started, dbType, host, port, database, sql) };
    }
    const parsed = JSON.parse(text);
    const data = parsed.data || [];
    const metaCols = parsed.meta || [];
    return {
      columns: metaCols.map((m) => m.name),
      rows: data,
      rowCount: data.length,
      ...meta(started, dbType, host, port, database, sql)
    };
  } catch (e) {
    clearTimeout(timer);
    if (e.name === "AbortError") throw new Error("ClickHouse \u67E5\u8BE2\u8D85\u65F6");
    throw e;
  }
}
function shapeResult(fields, rows, rowCount, started, dbType, host, port, database, sql) {
  const columns = fields ? fields.map((f) => f.name) : [];
  let shapedRows = [];
  if (fields && Array.isArray(rows)) {
    shapedRows = rows.map((row) => {
      const obj = {};
      fields.forEach((f, i) => {
        obj[f.name] = row[i];
      });
      return obj;
    });
  }
  return { columns, rows: shapedRows, rowCount: rowCount ?? shapedRows.length, ...meta(started, dbType, host, port, database, sql) };
}
function meta(started, dbType, host, port, database, sql) {
  return {
    elapsedMs: Date.now() - started,
    connectionName: `${dbType}://${host ?? ""}${port ? ":" + port : ""}/${database ?? ""}`.replace(/:\/\//, host ? "://" : ""),
    sql,
    directExecuted: true
  };
}
function mkError(code, message) {
  const err = new Error(message);
  err.code = code;
  return err;
}
function isSqlBlocked(result) {
  if (!result?.isError) return false;
  const text = extractText(result);
  if (!text) return false;
  const upper = text.toUpperCase();
  return upper.includes("SQL_BLOCKED") || upper.includes("HIGH-RISK SQL IS DISABLED") || upper.includes("HIGH RISK SQL") || upper.includes("WRITE DISABLED") || upper.includes("BLOCKED");
}
function extractText(result) {
  if (!result?.content) return "";
  if (Array.isArray(result.content)) {
    return result.content.map((c) => c?.text ?? "").join("");
  }
  return result.content?.text ?? "";
}

// service/src/engine/markdown-parser.mjs
function textOf(result) {
  return result?.content?.map((c) => c.text ?? "").join("\n") ?? "";
}
function parseMarkdownTable(text) {
  const lines = text.split("\n").map((l) => l.trim()).filter((l) => l.startsWith("|"));
  if (lines.length < 2) return { columns: [], rows: [] };
  const split = (line) => line.replace(/^\|/, "").replace(/\|$/, "").split("|").map((c) => c.trim());
  const columns = split(lines[0]);
  const rows = lines.slice(2).map((line) => {
    const cells = split(line);
    const row = {};
    columns.forEach((col, i) => {
      row[col] = cells[i] ?? "";
    });
    return row;
  });
  return { columns, rows };
}
function pick(row, names) {
  for (const n of names) {
    const v = row[n];
    if (v !== void 0 && v !== "") return v;
  }
  return "";
}
function parseBulletList(text) {
  const items = [];
  for (const line of text.split("\n")) {
    const m = line.trim().match(/^[-*]\s*(.+)$/);
    if (m) items.push(m[1].trim());
  }
  return items;
}
function parseTableList(text) {
  const tables = [];
  for (const item of parseBulletList(text)) {
    const m = item.match(/^(.+?)\s*\(([^)]+)\)(?:\s*--.*)?$/);
    if (m) {
      tables.push({ name: m[1].trim(), kind: m[2].trim() });
    } else {
      tables.push({ name: item.replace(/\s+--.*$/, "").trim(), kind: "" });
    }
  }
  if (tables.length === 0) {
    const { rows } = parseMarkdownTable(text);
    for (const row of rows) {
      const name = pick(row, ["Name", "name", "Table", "table", "Table Name", "\u8868\u540D"]);
      if (name) tables.push({ name, kind: pick(row, ["Type", "type", "Kind", "kind", "Table Type", "\u7C7B\u578B"]) });
    }
  }
  return tables;
}
function isPkMarker(cells) {
  const hay = cells.join(" ").toUpperCase();
  return hay.includes("(PK)") || /\bPK\b/.test(hay) || /\bPRI\b/.test(hay) || /\bPRIMARY KEY\b/.test(hay);
}
function parseDescribeColumns(rows) {
  return rows.map((row) => {
    const nameCell = pick(row, ["Column", "Name", "name"]);
    const keyCell = pick(row, ["Key", "KeyType", "Key type", "keys"]);
    const commentCell = pick(row, ["Comment", "comment"]);
    const isPrimaryKey = isPkMarker([nameCell, keyCell, commentCell]);
    const name = nameCell.replace(/\s*\((?:PK|PRIMARY KEY)\)\s*/gi, "").trim();
    const defaultCell = pick(row, ["Default", "default"]);
    return {
      name,
      type: pick(row, ["Type", "type"]),
      nullable: (pick(row, ["Nullable", "nullable"]) || "YES").toUpperCase() !== "NO",
      hasDefault: defaultCell.length > 0,
      defaultValue: defaultCell,
      comment: commentCell,
      isPrimaryKey
    };
  });
}
function dedupeConnections(connections) {
  const seenIds = /* @__PURE__ */ new Set();
  const seenNames = /* @__PURE__ */ new Set();
  const unique = [];
  for (const connection of connections) {
    const id = (connection.id ?? "").trim();
    const name = (connection.name ?? "").trim();
    if (!id && !name) {
      unique.push(connection);
      continue;
    }
    if (id && seenIds.has(id) || name && seenNames.has(name)) continue;
    if (id) seenIds.add(id);
    if (name) seenNames.add(name);
    unique.push(connection);
  }
  return unique;
}
function parseConnections(text) {
  const { rows } = parseMarkdownTable(text);
  return rows.map((row) => ({
    id: pick(row, ["ID", "Id", "id"]),
    name: pick(row, ["Name", "name"]),
    groupPath: pick(row, ["Group Path", "GroupPath", "group"]),
    type: pick(row, ["Type", "type", "DB Type"]),
    host: pick(row, ["Host", "host"]),
    port: Number(pick(row, ["Port", "port"])) || 0,
    database: pick(row, ["Database", "database", "DB"])
  }));
}
function classifyError(raw) {
  if (!raw) return { code: "UNKNOWN", detail: "" };
  if (raw.includes("SQL_BLOCKED")) return { code: "SQL_BLOCKED", detail: raw };
  if (raw.includes("DBX_NOT_RUNNING")) return { code: "DBX_NOT_RUNNING", detail: raw };
  if (/connection.*not.*found|ConnectionNotFound/i.test(raw)) return { code: "CONNECTION_NOT_FOUND", detail: raw };
  if (/MCP_READ_ONLY|read-only mode/i.test(raw)) return { code: "READ_ONLY", detail: raw };
  if (/already exists/i.test(raw)) return { code: "CONNECTION_EXISTS", detail: raw };
  if (/INVALID_CONNECTION_TYPE|Unsupported database type|INVALID_CONNECTION|Port is required/i.test(raw))
    return { code: "INVALID_PARAMS", detail: raw };
  if (/timed?\s*out|timeout/i.test(raw)) return { code: "TIMEOUT", detail: raw };
  if (/connection|failed|refused|ECONN|TABLE_LIST_ERROR|CONNECTION_LOAD_ERROR|CONNECTION_SAVE_ERROR/i.test(raw))
    return { code: "CONNECTION_FAILED", detail: raw };
  return { code: "UNKNOWN", detail: raw };
}
function extractDuration(text) {
  const m = text.match(/(\d+(?:\.\d+)?)\s*(ms|s)\b/i);
  return m ? m[0] : "";
}

// service/src/engine/request-router.mjs
function clampRowLimit(rowLimit) {
  const value = Number.isFinite(rowLimit) ? Math.trunc(rowLimit) : DEFAULT_ROW_LIMIT;
  return Math.min(Math.max(value, 1), MAX_ROW_LIMIT);
}
function clampTimeout(timeoutMs) {
  const value = Number.isFinite(timeoutMs) ? Math.trunc(timeoutMs) : 3e4;
  return Math.min(Math.max(value, 1e3), MAX_TIMEOUT_MS);
}
function extractText2(result, toolName) {
  const text = textOf(result);
  if (result.isError) {
    const err = classifyError(text);
    throw engineError(err.code, `${toolName} failed: ${err.detail}`, text);
  }
  return text;
}
function toDbxAddParams(body) {
  const args = { name: body.name, db_type: body.dbType, host: body.host };
  if (body.port) args.port = body.port;
  if (body.username) args.username = body.username;
  if (body.password) args.password = body.password;
  if (body.database) args.database = body.database;
  if (body.ssl !== void 0) args.ssl = body.ssl === true;
  if (!args.host && body.file) args.host = body.file;
  return args;
}
function createRouter({ auth, now = () => Date.now() } = {}) {
  if (!auth) throw new Error("createRouter \u9700\u8981 auth");
  const mcpClient = () => getDbxMcpClient();
  const routeDefs = [
    // === 健康检查 ===
    ["/health", "GET", false, async () => {
      let dbxInfo = { status: "unknown" };
      try {
        await mcpClient().ensureInitialized();
        dbxInfo = { status: "connected" };
      } catch (e) {
        dbxInfo = { status: "error", message: e.message };
      }
      return {
        status: "ok",
        version: ENGINE_VERSION,
        protocol: PROTOCOL_VERSION,
        pid: process.pid,
        node: process.version,
        platform: `${process.platform}-${process.arch}`,
        uptimeMs: Math.round(process.uptime() * 1e3),
        auth: auth?.enabled ? "enabled" : "disabled",
        dbx: dbxInfo,
        drivers: [{ id: "dbx-cli", label: "dbx CLI (100+ databases)", tier: "first-class", ready: true }]
      };
    }],
    // === 连接管理 ===
    ["/connections", "GET", true, async () => {
      const result = await mcpClient().callTool("dbx_list_connections", {});
      const text = extractText2(result, "dbx_list_connections");
      const raw = parseConnections(text);
      return { connections: dedupeConnections(raw) };
    }],
    ["/connections", "POST", true, async ({ body }) => {
      if (!body?.name || !body?.dbType) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 name / dbType");
      const dbxArgs = toDbxAddParams(body);
      const result = await mcpClient().callTool("dbx_add_connection", dbxArgs);
      const text = extractText2(result, "dbx_add_connection");
      const idMatch = text.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);
      return { id: idMatch?.[0] ?? "", name: body.name, detail: text };
    }],
    ["/connections", "DELETE", true, async ({ body }) => {
      const name = body?.name;
      if (!name) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connection name");
      const result = await mcpClient().callTool("dbx_remove_connection", { connection_name: name });
      extractText2(result, "dbx_remove_connection");
      return { deleted: name };
    }],
    ["/connections/test", "POST", true, async ({ body }) => {
      const connectionName = body?.connectionName;
      let tempName = null;
      let actualName = connectionName;
      if (!connectionName && body?.draft) {
        tempName = `astravia-test-${Date.now().toString(36)}`;
        const addResult = await mcpClient().callTool("dbx_add_connection", toDbxAddParams({ ...body.draft, name: tempName }));
        extractText2(addResult, "dbx_add_connection");
        actualName = tempName;
      }
      if (!actualName) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connectionName \u6216 draft");
      try {
        const testResult = await mcpClient().callTool("dbx_list_tables", { connection_name: actualName });
        const text = extractText2(testResult, "dbx_list_tables");
        const tableCount = parseTableList(text).length;
        return { tableCount, detail: text };
      } finally {
        if (tempName) {
          try {
            await mcpClient().callTool("dbx_remove_connection", { connection_name: tempName });
          } catch {
          }
        }
      }
    }],
    // === 查询执行 ===
    ["/query", "POST", true, async ({ body }) => {
      const connectionName = body?.connectionName ?? body?.connection?.name;
      if (!connectionName) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connectionName");
      const sql = body?.sql;
      if (typeof sql !== "string" || sql.trim().length === 0) throw engineError("BAD_REQUEST", "SQL \u4E0D\u80FD\u4E3A\u7A7A");
      const classified = classifyQuery(sql);
      const timeoutMs = clampTimeout(body?.timeoutMs);
      const rowLimit = clampRowLimit(body?.rowLimit);
      const started = now();
      let result;
      try {
        result = await mcpClient().callTool(
          "dbx_execute_query",
          { connection_name: connectionName, sql },
          timeoutMs
        );
      } catch (e) {
        const msg = e?.message ?? String(e);
        throw engineError("DBX_MCP_ERROR", `dbx-mcp \u8C03\u7528\u5931\u8D25: ${msg}`);
      }
      if (!result.isError) {
        const text = extractText2(result, "dbx_execute_query");
        const { columns, rows } = parseMarkdownTable(text);
        const rowCount = rows.length;
        const truncated = rowLimit > 0 && rowCount > rowLimit;
        const visibleRows = truncated ? rows.slice(0, rowLimit) : rows;
        return {
          connection: connectionName,
          kind: classified.kind,
          statement_count: classified.statements.length,
          columns,
          rows: visibleRows,
          row_count: rowCount,
          truncated,
          row_limit: rowLimit,
          duration_ms: now() - started,
          duration_hint: extractDuration(text),
          raw_text: text,
          affected_rows: (() => {
            const m = text.match(/(\d+)\s*row(?:s)?\s*(?:affected|inserted|updated|deleted)/i);
            return m ? parseInt(m[1], 10) : null;
          })()
        };
      }
      const errorText = textOf(result);
      const err = classifyError(errorText);
      const conn = body?.connection;
      const dbType = (conn?.dbType ?? conn?.db_type ?? "").toLowerCase();
      const supportedByDirect = DRIVER_FAMILY[dbType] != null;
      const shouldFallback = (err.code === "SQL_BLOCKED" || isSqlBlocked(result)) && supportedByDirect;
      if (conn && dbType && shouldFallback) {
        try {
          const direct = await executeDirect({
            dbType,
            host: conn.host,
            port: conn.port,
            username: conn.username ?? conn.user,
            password: conn.password,
            database: conn.database,
            ssl: conn.ssl,
            sql,
            timeoutMs
          });
          const rowCount = direct.rows?.length ?? direct.rowCount ?? 0;
          const truncated = rowLimit > 0 && rowCount > rowLimit;
          const visibleRows = truncated ? direct.rows.slice(0, rowLimit) : direct.rows;
          return {
            connection: connectionName,
            kind: classified.kind,
            statement_count: classified.statements.length,
            columns: direct.columns ?? [],
            rows: visibleRows,
            row_count: rowCount,
            truncated,
            row_limit: rowLimit,
            duration_ms: direct.elapsedMs ?? now() - started,
            duration_hint: "direct-driver",
            raw_text: null,
            affected_rows: direct.rowCount ?? null,
            direct_executed: true
          };
        } catch (directErr) {
          const directMsg = directErr?.message ?? String(directErr);
          const combinedErr = engineError(
            directErr?.code ?? "DIRECT_DRIVER_ERROR",
            `dbx-mcp \u6267\u884C\u5931\u8D25 + \u76F4\u8FDE\u56DE\u9000\u4E5F\u5931\u8D25\uFF1A${directMsg}`,
            `${errorText}
--- direct-driver ---
${directMsg}`
          );
          throw combinedErr;
        }
      }
      throw engineError(err.code, `dbx_execute_query failed: ${err.detail}`, errorText);
    }],
    // === 对象浏览 ===
    ["/tables", "POST", true, async ({ body }) => {
      const connectionName = body?.connectionName ?? body?.connection?.name;
      if (!connectionName) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connectionName");
      const scope = body?.scope ?? {};
      const args = { connection_name: connectionName };
      if (scope.schema) args.schema = scope.schema;
      if (scope.database) args.database = scope.database;
      const result = await mcpClient().callTool("dbx_list_tables", args);
      const text = extractText2(result, "dbx_list_tables");
      return { connection: connectionName, tables: parseTableList(text) };
    }],
    ["/describe", "POST", true, async ({ body }) => {
      const connectionName = body?.connectionName ?? body?.connection?.name;
      const target = body?.target ?? { schema: body?.schema, table: body?.table };
      if (!connectionName) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connectionName");
      if (!target?.table) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 table");
      const args = { connection_name: connectionName, table: target.table };
      if (target.schema) args.schema = target.schema;
      const result = await mcpClient().callTool("dbx_describe_table", args);
      const text = extractText2(result, "dbx_describe_table");
      const { rows } = parseMarkdownTable(text);
      return { connection: connectionName, table: target.table, columns: parseDescribeColumns(rows) };
    }],
    ["/schema-context", "POST", true, async ({ body }) => {
      const connectionName = body?.connectionName;
      if (!connectionName) throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connectionName");
      const result = await mcpClient().callTool("dbx_get_schema_context", { connection_name: connectionName });
      const text = extractText2(result, "dbx_get_schema_context");
      return { connection: connectionName, schema: text };
    }]
  ];
  const routes = /* @__PURE__ */ new Map();
  for (const [pathname, method, auth2, handler] of routeDefs) {
    if (!routes.has(pathname)) routes.set(pathname, /* @__PURE__ */ new Map());
    routes.get(pathname).set(method, { auth: auth2, handler });
  }
  async function handle(request) {
    const { method = "GET", pathname, headers = {}, body = null } = request ?? {};
    const methodMap = routes.get(pathname);
    if (!methodMap) {
      const error = engineError("NOT_FOUND", `\u672A\u77E5\u8DEF\u5F84\uFF1A${pathname}`);
      return { status: httpStatusForCode(error.code), body: fail(error) };
    }
    const route = methodMap.get(method);
    if (!route) {
      const allowed = [...methodMap.keys()].join(", ");
      const error = engineError("METHOD_NOT_ALLOWED", `${pathname} \u53EA\u63A5\u53D7 ${allowed}`);
      return { status: httpStatusForCode(error.code), body: fail(error) };
    }
    try {
      if (route.auth) auth.verify(headers);
      const data = await route.handler({ body, headers });
      return { status: 200, body: ok(data) };
    } catch (error) {
      const normalized = normalizeThrown(error);
      return { status: httpStatusForCode(normalized.code), body: fail(normalized) };
    }
  }
  return { handle, routes };
}

// service/src/http-server.mjs
var HOST = "127.0.0.1";
var SECRET_KEY_ENV = "ASTRAVIA_SERVICE_SECRET_ENGINE_KEY";
function emit(event, payload = {}) {
  process.stdout.write(
    `${JSON.stringify({ event, version: ENGINE_VERSION, ts: (/* @__PURE__ */ new Date()).toISOString(), ...payload })}
`
  );
}
function parseArgs(argv) {
  const args = { port: 0, dataDir: null, authDisabled: false, help: false };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--port") args.port = Number(argv[index += 1]);
    else if (token === "--data") args.dataDir = argv[index += 1] ?? null;
    else if (token === "--auth-disabled") args.authDisabled = true;
    else if (token === "--help" || token === "-h") args.help = true;
  }
  return args;
}
function digest(value) {
  return createHash("sha256").update(value).digest();
}
function createAuth({ token, disabled = false } = {}) {
  const enabled = !disabled && typeof token === "string" && token.length > 0;
  const expected = enabled ? digest(token) : null;
  return {
    enabled,
    verify(headers = {}) {
      if (!enabled) return;
      const header = headers.authorization ?? headers.Authorization ?? "";
      const bearer = /^bearer\s+(.+)$/i.exec(String(header));
      const presented = bearer ? bearer[1].trim() : String(headers["x-dbx-token"] ?? "").trim();
      if (!presented || !timingSafeEqual(digest(presented), expected)) {
        throw engineError("UNAUTHORIZED", "\u7F3A\u5C11\u6216\u65E0\u6548\u7684\u5F15\u64CE\u8BBF\u95EE\u4EE4\u724C");
      }
    }
  };
}
function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    let failed = false;
    req.on("data", (chunk) => {
      if (failed) return;
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        failed = true;
        reject(engineError("PAYLOAD_TOO_LARGE", `\u8BF7\u6C42\u4F53\u8D85\u8FC7 ${MAX_BODY_BYTES} \u5B57\u8282`));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (failed) return;
      const raw = Buffer.concat(chunks).toString("utf8").trim();
      if (raw.length === 0) return resolve(null);
      try {
        resolve(JSON.parse(raw));
      } catch (error) {
        reject(engineError("BAD_REQUEST", `\u8BF7\u6C42\u4F53\u4E0D\u662F\u5408\u6CD5 JSON\uFF1A${error instanceof Error ? error.message : error}`));
      }
    });
    req.on("error", (error) => {
      if (!failed) reject(engineError("BAD_REQUEST", error instanceof Error ? error.message : String(error)));
    });
  });
}
function createEngineServer({ token, dataDir = null, authDisabled = false } = {}) {
  const auth = createAuth({ token, disabled: authDisabled });
  const router = createRouter({ auth });
  const server = createServer(async (req, res) => {
    const send = (status, body) => {
      if (res.writableEnded) return;
      const payload = stringifyJson(body);
      res.writeHead(status, {
        "content-type": "application/json; charset=utf-8",
        "content-length": Buffer.byteLength(payload),
        "cache-control": "no-store"
      });
      res.end(payload);
    };
    let url;
    try {
      url = new URL(req.url ?? "/", `http://${HOST}`);
    } catch {
      const error = engineError("BAD_REQUEST", `\u975E\u6CD5\u8BF7\u6C42\u8DEF\u5F84\uFF1A${req.url}`);
      return send(400, { ok: false, error: { code: error.code, message: error.message } });
    }
    try {
      const body = req.method === "POST" || req.method === "DELETE" ? await readJsonBody(req) : null;
      if (req.method === "POST" && url.pathname === "/mcp") {
        auth.verify(req.headers);
        const rpc = body ?? {};
        const id = rpc.id ?? null;
        const client2 = getDbxMcpClient();
        try {
          if (rpc.method === "initialize") {
            await client2.ensureInitialized();
            return send(200, { jsonrpc: "2.0", id, result: { protocolVersion: "2024-11-05", capabilities: { tools: {} }, serverInfo: { name: "dbx-pro", version: ENGINE_VERSION } } });
          }
          if (rpc.method === "tools/list") {
            const list = await client2.listTools();
            return send(200, { jsonrpc: "2.0", id, result: { tools: list } });
          }
          if (rpc.method === "tools/call") {
            const params = rpc.params ?? {};
            const name = params.name;
            const args = params.arguments ?? {};
            if (!name) return send(200, { jsonrpc: "2.0", id, error: { code: -32602, message: "Missing tool name" } });
            const callResult = await client2.callTool(name, args);
            return send(200, { jsonrpc: "2.0", id, result: callResult });
          }
          return send(200, { jsonrpc: "2.0", id, error: { code: -32601, message: `Unsupported MCP method: ${rpc.method}` } });
        } catch (e) {
          emit("mcp-error", { method: rpc.method, message: e.message });
          return send(200, { jsonrpc: "2.0", id, result: { isError: true, content: [{ type: "text", text: e.message }] } });
        }
      }
      const outcome = await router.handle({
        method: req.method,
        pathname: url.pathname,
        headers: req.headers,
        body
      });
      send(outcome.status, outcome.body);
    } catch (error) {
      const code = error?.code ?? "INTERNAL";
      const status = code === "PAYLOAD_TOO_LARGE" ? 413 : code === "BAD_REQUEST" ? 400 : 500;
      emit("request-error", { path: url.pathname, code });
      send(status, { ok: false, error: { code, message: error?.message ?? String(error) } });
    }
  });
  server.on("clientError", (error, socket) => {
    emit("request-error", { path: null, code: "CLIENT_ERROR", message: error.message });
    if (socket.writable) socket.end("HTTP/1.1 400 Bad Request\r\n\r\n");
  });
  return { server, auth, router, dataDir };
}
async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    process.stdout.write(
      "dbx-pro engine (dbx-mcp bridge)\n  --port <n>        listen port (0 = random)\n  --data <dir>      service data directory (dbx-mcp stores dbx.db here)\n  --auth-disabled   disable token auth (local dev only)\n"
    );
    return;
  }
  if (!Number.isInteger(args.port) || args.port < 0 || args.port > 65535) {
    emit("server-error", { code: "BAD_PORT", message: `\u975E\u6CD5\u7AEF\u53E3\uFF1A${args.port}` });
    process.exit(1);
  }
  const token = process.env[SECRET_KEY_ENV];
  if (typeof token !== "string" || token.length === 0) {
    if (!args.authDisabled) {
      emit("server-error", {
        code: "NO_SECRET",
        message: `\u7F3A\u5C11\u5F15\u64CE\u8BBF\u95EE\u4EE4\u724C\uFF08\u73AF\u5883\u53D8\u91CF ${SECRET_KEY_ENV} \u672A\u8BBE\u7F6E\u6216\u4E3A\u7A7A\uFF09\uFF1B\u672C\u5730\u8C03\u8BD5\u8BF7\u663E\u5F0F\u4F20 --auth-disabled`
      });
      process.exit(1);
    }
  }
  const { server, auth } = createEngineServer({
    token,
    dataDir: args.dataDir,
    authDisabled: args.authDisabled
  });
  if (!auth.enabled) emit("auth-disabled", { reason: args.authDisabled ? "flag" : "no-secret" });
  await new Promise((resolve) => {
    server.on("error", (error) => {
      emit("server-error", { code: error.code ?? "SERVER_ERROR", message: error.message });
      process.exit(1);
    });
    server.listen(args.port, HOST, () => resolve());
  });
  const address = server.address();
  emit("listening", {
    host: HOST,
    port: typeof address === "object" && address ? address.port : args.port,
    pid: process.pid,
    node: process.version,
    protocol: PROTOCOL_VERSION,
    auth: auth.enabled ? "enabled" : "disabled",
    dataDir: args.dataDir,
    backend: "dbx-mcp"
  });
  let closing = false;
  const shutdown = async (signal) => {
    if (closing) return;
    closing = true;
    await new Promise((resolve) => server.close(() => resolve()));
    try {
      await disposeDbxMcpClient();
    } catch {
    }
    emit("shutdown", { signal });
    process.exit(0);
  };
  process.on("SIGTERM", () => void shutdown("SIGTERM"));
  process.on("SIGINT", () => void shutdown("SIGINT"));
}
main();
export {
  createAuth,
  createEngineServer
};
