// dbx-pro engine bundle — generated by scripts/build-engine.mjs; DO NOT EDIT.


// service/src/http-server.mjs
import { createHash as createHash2, timingSafeEqual } from "node:crypto";
import { createServer } from "node:http";

// service/src/engine/protocol.mjs
var ENGINE_VERSION = "0.1.1";
var PROTOCOL_VERSION = 1;
var MAX_BODY_BYTES = 8 * 1024 * 1024;
var DEFAULT_ROW_LIMIT = 500;
var MAX_ROW_LIMIT = 5e3;
var MAX_TIMEOUT_MS = 3e5;
var STATUS_BY_CODE = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PAYLOAD_TOO_LARGE: 413,
  WRITE_BLOCKED: 403,
  DDL_BLOCKED: 403,
  CONFIRM_MISMATCH: 403,
  PROD_WRITE_BLOCKED: 403,
  DRIVER_UNSUPPORTED: 501,
  DRIVER_ERROR: 502,
  CONNECTION_ERROR: 502,
  TIMEOUT: 504,
  INTERNAL: 500
});
function httpStatusForCode(code) {
  return STATUS_BY_CODE[code] ?? 500;
}
var EngineError = class extends Error {
  constructor(code, message, detail) {
    super(message);
    this.name = "EngineError";
    this.code = code;
    this.detail = detail;
    this.engineError = true;
  }
};
function engineError(code, message, detail) {
  return new EngineError(code, message, detail);
}
function isEngineError(value) {
  return Boolean(value) && typeof value === "object" && value.engineError === true && typeof value.code === "string";
}
function normalizeThrown(thrown) {
  if (isEngineError(thrown)) return thrown;
  const message = thrown instanceof Error ? thrown.message : String(thrown);
  const rawCode = thrown && typeof thrown === "object" && typeof thrown.code === "string" ? thrown.code : null;
  if (rawCode === "ERR_SQLITE_ERROR" || rawCode === "ERR_OUT_OF_RANGE") {
    return new EngineError("DRIVER_ERROR", message, { driverCode: rawCode });
  }
  return new EngineError("INTERNAL", message, rawCode ? { driverCode: rawCode } : void 0);
}
function ok(data) {
  return { ok: true, data };
}
function fail(thrown) {
  const error = normalizeThrown(thrown);
  return {
    ok: false,
    error: error.detail === void 0 ? { code: error.code, message: error.message } : { code: error.code, message: error.message, detail: error.detail }
  };
}
function isSafeBigInt(value) {
  return value <= BigInt(Number.MAX_SAFE_INTEGER) && value >= BigInt(Number.MIN_SAFE_INTEGER);
}
function jsonReplacer(_key, value) {
  if (typeof value === "bigint") {
    return isSafeBigInt(value) ? Number(value) : value.toString();
  }
  if (value instanceof Uint8Array) {
    return {
      __type: "blob",
      bytes: value.byteLength,
      base64: Buffer.from(value).toString("base64")
    };
  }
  return value;
}
function stringifyJson(value) {
  return JSON.stringify(value, jsonReplacer);
}

// service/src/engine/connection-pool.mjs
var ConnectionPool = class {
  constructor({ idleTtlMs = 3e5, now = () => Date.now() } = {}) {
    this.idleTtlMs = idleTtlMs;
    this.now = now;
    this.entries = /* @__PURE__ */ new Map();
    this.pending = /* @__PURE__ */ new Map();
    this.invalidations = 0;
  }
  /**
   * 借出句柄。openHandle 由调用方提供（通常是 `() => driver.acquire(spec)`），
   * 池只负责身份复用与生命周期，不依赖驱动契约。
   */
  async acquire(key, openHandle) {
    const existing = this.entries.get(key);
    if (existing) {
      existing.lastUsed = this.now();
      return existing.handle;
    }
    const inflight = this.pending.get(key);
    if (inflight) return inflight;
    const opening = (async () => {
      try {
        const handle = await openHandle();
        this.entries.set(key, { handle, lastUsed: this.now() });
        return handle;
      } catch (error) {
        if (isEngineError(error)) throw error;
        throw engineError("CONNECTION_ERROR", error instanceof Error ? error.message : String(error));
      } finally {
        this.pending.delete(key);
      }
    })();
    this.pending.set(key, opening);
    return opening;
  }
  /**
   * 借出句柄执行 fn。**任何**抛出都会让该连接失效
   * （网络抖动或语法错误之后，句柄状态已不可信）。
   */
  async withConnection(key, openHandle, fn) {
    const handle = await this.acquire(key, openHandle);
    try {
      const result = await fn(handle);
      const entry = this.entries.get(key);
      if (entry) entry.lastUsed = this.now();
      return result;
    } catch (error) {
      await this.invalidate(key);
      throw error;
    }
  }
  async invalidate(key) {
    const entry = this.entries.get(key);
    if (!entry) return;
    this.entries.delete(key);
    this.invalidations += 1;
    try {
      await entry.handle.close();
    } catch {
    }
  }
  async reap() {
    const deadline = this.now() - this.idleTtlMs;
    for (const [key, entry] of [...this.entries]) {
      if (entry.lastUsed <= deadline) await this.invalidate(key);
    }
  }
  async closeAll() {
    const keys = [...this.entries.keys()];
    for (const key of keys) await this.invalidate(key);
    this.pending.clear();
  }
  stats() {
    const now = this.now();
    return {
      size: this.entries.size,
      invalidations: this.invalidations,
      connections: [...this.entries.entries()].map(([key, entry]) => ({
        // key 是 8 位摘要，不含任何凭据，可安全回给 UI 做诊断
        key: key.slice(0, 8),
        idleMs: now - entry.lastUsed
      }))
    };
  }
};

// service/src/engine/request-router.mjs
import { createHash } from "node:crypto";

// service/src/engine/query-guard.mjs
var READ_LEADERS = /* @__PURE__ */ new Set(["SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "USE", "VALUES"]);
var DDL_KEYWORDS = ["CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME"];
var DDL_LEADERS = new Set(DDL_KEYWORDS);
var DDL_KEYWORD_RE = new RegExp(`\\b(${DDL_KEYWORDS.join("|")})\\b`);
var WRITE_KEYWORDS = [
  "INSERT",
  "UPDATE",
  "DELETE",
  "REPLACE",
  "MERGE",
  "UPSERT",
  "TRUNCATE",
  "CREATE",
  "ALTER",
  "DROP",
  "GRANT",
  "REVOKE",
  "COMMENT",
  "CALL",
  "EXEC",
  "EXECUTE",
  "DO",
  "VACUUM",
  "REINDEX",
  "COPY",
  "LOAD",
  "LOCK",
  "ATTACH",
  "DETACH",
  "RENAME",
  "ANALYZE",
  "SET"
];
var WRITE_KEYWORD_RE = new RegExp(`\\b(${WRITE_KEYWORDS.join("|")})\\b`);
var DESTRUCTIVE_LEADERS = /* @__PURE__ */ new Set([
  "DELETE",
  "UPDATE",
  "TRUNCATE",
  "DROP",
  "ALTER",
  "VACUUM",
  "REINDEX",
  "GRANT",
  "REVOKE",
  "ATTACH",
  "DETACH",
  "REPLACE",
  "MERGE"
]);
var QUOTE_CLOSERS = { "'": "'", '"': '"', "`": "`", "[": "]" };
function scanSql(sql, { onCode, onLiteral }) {
  const text = String(sql ?? "");
  const length = text.length;
  let index = 0;
  let code = "";
  const flushCode = () => {
    if (code.length > 0) {
      onCode(code);
      code = "";
    }
  };
  while (index < length) {
    const char = text[index];
    const closer = QUOTE_CLOSERS[char];
    if (closer !== void 0) {
      flushCode();
      let literal = char;
      index += 1;
      while (index < length) {
        const inner = text[index];
        literal += inner;
        if (inner === closer) {
          if (closer !== "]" && text[index + 1] === closer) {
            literal += text[index + 1];
            index += 2;
            continue;
          }
          index += 1;
          break;
        }
        index += 1;
      }
      onLiteral(literal);
      continue;
    }
    if (char === "-" && text[index + 1] === "-") {
      while (index < length && text[index] !== "\n" && text[index] !== "\r") index += 1;
      code += " ";
      continue;
    }
    if (char === "/" && text[index + 1] === "*") {
      index += 2;
      while (index < length && !(text[index] === "*" && text[index + 1] === "/")) index += 1;
      index = Math.min(index + 2, length);
      code += " ";
      continue;
    }
    code += char;
    index += 1;
  }
  flushCode();
}
function stripSqlComments(sql) {
  let stripped = "";
  scanSql(sql, {
    onCode: (chunk) => {
      stripped += chunk;
    },
    onLiteral: (literal) => {
      stripped += literal;
    }
  });
  return stripped.trim();
}
function keywords(sql) {
  return stripSqlComments(sql).toUpperCase().split(/[^A-Z0-9_$]+/).filter((token) => token.length > 0);
}
function firstKeyword(sql) {
  const tokens = keywords(sql);
  return tokens.length > 0 ? tokens[0] : "";
}
function isWriteStatement(sql) {
  const cleaned = stripSqlComments(sql);
  if (cleaned.length === 0) return false;
  const tokens = keywords(sql);
  if (tokens.length === 0) return false;
  const [first, second] = tokens;
  if (first === "EXPLAIN" && second === "ANALYZE") {
    return isWriteStatement(cleaned.slice(cleaned.toUpperCase().indexOf("ANALYZE") + "ANALYZE".length));
  }
  if (first === "WITH") {
    return WRITE_KEYWORD_RE.test(cleaned.toUpperCase());
  }
  if (READ_LEADERS.has(first)) return false;
  return true;
}
function isDdlStatement(sql) {
  const cleaned = stripSqlComments(sql);
  if (cleaned.length === 0) return false;
  const first = firstKeyword(cleaned);
  if (DDL_LEADERS.has(first)) return true;
  if (first === "WITH") return DDL_KEYWORD_RE.test(cleaned.toUpperCase());
  return false;
}
function isDestructiveStatement(sql) {
  if (isDdlStatement(sql)) return true;
  return DESTRUCTIVE_LEADERS.has(firstKeyword(sql));
}
function splitStatements(sql) {
  const statements = [];
  let current = "";
  const flush = () => {
    const trimmed = current.trim();
    if (trimmed.length > 0) statements.push(trimmed);
    current = "";
  };
  scanSql(sql, {
    onCode: (chunk) => {
      for (const char of chunk) {
        if (char === ";") flush();
        else current += char;
      }
    },
    onLiteral: (literal) => {
      current += literal;
    }
  });
  flush();
  return statements;
}
function classifySql(sql) {
  if (isDdlStatement(sql)) return "ddl";
  if (!isWriteStatement(sql)) return "read";
  return isDestructiveStatement(sql) ? "destructive" : "write";
}
function classifyQuery(sql) {
  const statements = splitStatements(sql);
  const kinds = statements.map(classifySql);
  const requiresConfirmation = kinds.includes("ddl") || kinds.includes("destructive");
  let kind = "read";
  for (const current of kinds) {
    if (current === "ddl") kind = "ddl";
    else if (current === "destructive" && kind !== "ddl") kind = "destructive";
    else if (current === "write" && kind === "read") kind = "write";
  }
  return { kind, kinds, statements, requiresConfirmation };
}
function guardQuery({ sql, allowWrites = false, confirmedWriteSql } = {}) {
  if (typeof sql !== "string" || sql.trim().length === 0) {
    throw engineError("BAD_REQUEST", "SQL \u4E0D\u80FD\u4E3A\u7A7A");
  }
  const classified = classifyQuery(sql);
  if (classified.statements.length === 0) {
    throw engineError("BAD_REQUEST", "\u6CA1\u6709\u53EF\u6267\u884C\u7684 SQL \u8BED\u53E5\uFF08\u53EF\u80FD\u53EA\u6709\u6CE8\u91CA\uFF09");
  }
  if (classified.kind === "read") return classified;
  if (!allowWrites) {
    if (classified.kind === "ddl") {
      throw engineError("DDL_BLOCKED", "\u5F53\u524D\u8FDE\u63A5\u672A\u5F00\u542F\u5199\u6743\u9650\uFF0CDDL \u8BED\u53E5\u5DF2\u88AB\u62E6\u622A", {
        statementCount: classified.statements.length,
        kind: classified.kind
      });
    }
    throw engineError("WRITE_BLOCKED", "\u5F53\u524D\u8FDE\u63A5\u672A\u5F00\u542F\u5199\u6743\u9650\uFF0C\u5199\u8BED\u53E5\u5DF2\u88AB\u62E6\u622A", {
      statementCount: classified.statements.length,
      kind: classified.kind
    });
  }
  if (classified.requiresConfirmation && confirmedWriteSql !== sql) {
    throw engineError(
      "CONFIRM_MISMATCH",
      "\u5371\u9669\u8BED\u53E5\u9700\u8981\u6309\u539F\u6587\u786E\u8BA4\u540E\u624D\u53EF\u6267\u884C\uFF08\u786E\u8BA4\u6587\u672C\u4E0E\u5B9E\u9645 SQL \u4E0D\u4E00\u81F4\uFF09",
      { statementCount: classified.statements.length, kind: classified.kind }
    );
  }
  return classified;
}

// service/src/driver-registry.mjs
var DRIVER_TABLE = Object.freeze([
  {
    id: "sqlite",
    label: "SQLite",
    family: "sqlite",
    tier: "first-class",
    defaultPort: 0,
    fileBased: true,
    aliases: ["sqlite3"]
  }
]);
var PENDING_DRIVERS = Object.freeze([
  { id: "postgres", label: "PostgreSQL", family: "postgres", tier: "experimental", defaultPort: 5432, reason: "driver.pending.postgres" },
  { id: "mysql", label: "MySQL", family: "mysql", tier: "experimental", defaultPort: 3306, reason: "driver.pending.mysql" },
  { id: "mariadb", label: "MariaDB", family: "mysql", tier: "experimental", defaultPort: 3306, reason: "driver.pending.mariadb" },
  { id: "mssql", label: "SQL Server", family: "mssql", tier: "experimental", defaultPort: 1433, reason: "driver.pending.mssql" },
  { id: "mongodb", label: "MongoDB", family: "mongodb", tier: "experimental", defaultPort: 27017, reason: "driver.pending.mongodb" },
  { id: "redis", label: "Redis", family: "redis", tier: "experimental", defaultPort: 6379, reason: "driver.pending.redis" },
  { id: "clickhouse", label: "ClickHouse", family: "clickhouse", tier: "experimental", defaultPort: 8123, reason: "driver.pending.clickhouse" },
  { id: "duckdb", label: "DuckDB", family: "duckdb", tier: "out-of-scope", defaultPort: 0, reason: "driver.pending.duckdb" },
  { id: "cloudflare-d1", label: "Cloudflare D1", family: "cloudflare-d1", tier: "out-of-scope", defaultPort: 0, reason: "driver.pending.cloudflare-d1" }
]);
var ALIASES = /* @__PURE__ */ new Map();
for (const entry of DRIVER_TABLE) {
  ALIASES.set(entry.id, entry.id);
  for (const alias of entry.aliases ?? []) ALIASES.set(alias, entry.id);
}
function normalizeDriverId(id) {
  if (typeof id !== "string" || id.trim().length === 0) return "";
  const raw = id.trim().toLowerCase();
  return ALIASES.get(raw) ?? raw;
}
function listDriverDescriptors() {
  return [
    ...DRIVER_TABLE.map((entry) => ({ ...entry, ready: true })),
    ...PENDING_DRIVERS.map((entry) => ({ ...entry, ready: false }))
  ];
}
var cache = /* @__PURE__ */ new Map();
async function loadDriver(id) {
  const normalized = normalizeDriverId(id);
  if (normalized.length === 0) throw engineError("BAD_REQUEST", "\u7F3A\u5C11\u8FDE\u63A5\u7C7B\u578B\uFF08dbType\uFF09");
  if (cache.has(normalized)) return cache.get(normalized);
  const entry = DRIVER_TABLE.find((candidate) => candidate.id === normalized);
  if (!entry) {
    const pending = PENDING_DRIVERS.find((candidate) => candidate.id === normalized);
    if (pending) {
      throw engineError("DRIVER_UNSUPPORTED", `\u9A71\u52A8 ${pending.label}\uFF08${pending.id}\uFF09\u5C1A\u672A\u5728\u63D2\u4EF6\u5F15\u64CE\u4E2D\u5B9E\u73B0`, {
        driver: pending.id,
        tier: pending.tier,
        reason: pending.reason
      });
    }
    throw engineError("DRIVER_UNSUPPORTED", `\u672A\u77E5\u7684\u6570\u636E\u5E93\u7C7B\u578B\uFF1A${id}`, { driver: String(id) });
  }
  const url = new URL(`./drivers/${entry.id}-driver.mjs`, import.meta.url);
  const module = await import(url.href);
  if (typeof module.createDriver !== "function") {
    throw engineError("INTERNAL", `\u9A71\u52A8\u6A21\u5757\u7F3A\u5C11 createDriver()\uFF1A${entry.id}`);
  }
  cache.set(normalized, module);
  return module;
}

// service/src/engine/request-router.mjs
function pick(source, ...keys) {
  for (const key of keys) {
    const value = source[key];
    if (value !== void 0 && value !== null && String(value).trim() !== "") return value;
  }
  return void 0;
}
function normalizePort(value) {
  if (value === void 0) return void 0;
  const port = Number(value);
  if (!Number.isInteger(port) || port <= 0 || port > 65535) {
    throw engineError("BAD_REQUEST", `\u7AEF\u53E3\u4E0D\u5408\u6CD5\uFF1A${value}`);
  }
  return port;
}
function normalizeSpec(raw) {
  const dbType = normalizeDriverId(pick(raw, "dbType", "db_type", "type"));
  if (dbType.length === 0) throw engineError("BAD_REQUEST", "\u7F3A\u5C11\u8FDE\u63A5\u7C7B\u578B\uFF08dbType\uFF09");
  const asString = (value) => typeof value === "string" && value.length > 0 ? value : void 0;
  return {
    id: asString(pick(raw, "id")),
    name: asString(pick(raw, "name")),
    dbType,
    host: asString(pick(raw, "host")),
    port: normalizePort(pick(raw, "port")),
    username: asString(pick(raw, "username", "user")),
    password: typeof raw.password === "string" ? raw.password : void 0,
    database: asString(pick(raw, "database", "db")),
    file: asString(pick(raw, "file", "filePath", "file_path")),
    readOnly: pick(raw, "readOnly", "read_only") === true
  };
}
function poolKeyFor(spec) {
  const identity = [
    spec.dbType,
    spec.host ?? "",
    spec.port ?? "",
    spec.database ?? "",
    spec.file ?? "",
    spec.username ?? "",
    spec.readOnly === true ? "ro" : "rw"
  ].join("|");
  const credential = typeof spec.password === "string" && spec.password.length > 0 ? createHash("sha256").update(spec.password).digest("hex").slice(0, 8) : "";
  return `${identity}|${credential}`;
}
function clampRowLimit(rowLimit) {
  const value = Number.isFinite(rowLimit) ? Math.trunc(rowLimit) : DEFAULT_ROW_LIMIT;
  return Math.min(Math.max(value, 1), MAX_ROW_LIMIT);
}
function clampTimeout(timeoutMs) {
  const value = Number.isFinite(timeoutMs) ? Math.trunc(timeoutMs) : 3e4;
  return Math.min(Math.max(value, 1e3), MAX_TIMEOUT_MS);
}
function requireConnection(body) {
  const raw = body?.connection ?? body?.conn;
  if (!raw || typeof raw !== "object") throw engineError("BAD_REQUEST", "\u7F3A\u5C11 connection");
  return normalizeSpec(raw);
}
function createRouter({ pool, auth, now = () => Date.now() } = {}) {
  if (!pool) throw new Error("createRouter \u9700\u8981 pool");
  const resolveDriver = async (spec) => {
    const module = await loadDriver(spec.dbType);
    return { module, driver: module.createDriver() };
  };
  const routes = /* @__PURE__ */ new Map([
    [
      "/health",
      {
        method: "GET",
        auth: false,
        handler: () => ({
          status: "ok",
          version: ENGINE_VERSION,
          protocol: PROTOCOL_VERSION,
          pid: process.pid,
          node: process.version,
          platform: `${process.platform}-${process.arch}`,
          uptimeMs: Math.round(process.uptime() * 1e3),
          auth: auth?.enabled ? "enabled" : "disabled",
          pool: pool.stats(),
          drivers: listDriverDescriptors()
        })
      }
    ],
    [
      "/test",
      {
        method: "POST",
        auth: true,
        handler: async ({ body, pool: connectionPool }) => {
          const spec = requireConnection(body);
          const { module, driver } = await resolveDriver(spec);
          const outcome = await connectionPool.withConnection(
            poolKeyFor(spec),
            () => driver.acquire(spec),
            (handle2) => handle2.test()
          );
          return { connection: spec.name ?? spec.id ?? null, ...outcome, driver: { id: module.descriptor.id, tier: module.descriptor.tier } };
        }
      }
    ],
    [
      "/catalog",
      {
        method: "POST",
        auth: true,
        handler: async ({ body, pool: connectionPool }) => {
          const spec = requireConnection(body);
          const { driver } = await resolveDriver(spec);
          const result = await connectionPool.withConnection(
            poolKeyFor(spec),
            () => driver.acquire(spec),
            (handle2) => handle2.catalog(body?.scope ?? {})
          );
          return { connection: spec.name ?? spec.id ?? null, ...result };
        }
      }
    ],
    [
      "/describe",
      {
        method: "POST",
        auth: true,
        handler: async ({ body, pool: connectionPool }) => {
          const spec = requireConnection(body);
          const target = body?.target ?? { schema: body?.schema, table: body?.table };
          const { driver } = await resolveDriver(spec);
          const result = await connectionPool.withConnection(
            poolKeyFor(spec),
            () => driver.acquire(spec),
            (handle2) => handle2.describe({ schema: target?.schema ?? "main", table: target?.table })
          );
          return { connection: spec.name ?? spec.id ?? null, ...result };
        }
      }
    ],
    [
      "/query",
      {
        method: "POST",
        auth: true,
        handler: async ({ body, pool: connectionPool }) => {
          const spec = requireConnection(body);
          const allowWrites = body?.allowWrites === true;
          const confirmedWriteSql = typeof body?.confirmedWriteSql === "string" ? body.confirmedWriteSql : void 0;
          const classified = guardQuery({ sql: body?.sql, allowWrites, confirmedWriteSql });
          const { driver } = await resolveDriver(spec);
          const timeoutMs = clampTimeout(body?.timeoutMs);
          const rowLimit = clampRowLimit(body?.rowLimit);
          const deadline = now() + timeoutMs;
          const shouldAbort = () => now() > deadline;
          const key = poolKeyFor(spec);
          const started = now();
          const statements = [];
          for (const statement of classified.statements) {
            statements.push(
              await connectionPool.withConnection(
                key,
                () => driver.acquire(spec),
                (handle2) => handle2.query({ sql: statement, rowLimit, shouldAbort })
              )
            );
          }
          const last = statements[statements.length - 1];
          return {
            connection: spec.name ?? spec.id ?? null,
            kind: classified.kind,
            statement_count: statements.length,
            statements,
            truncated: statements.some((entry) => entry.truncated),
            row_limit: rowLimit,
            timeout_ms: timeoutMs,
            duration_ms: now() - started,
            // 顶层镜像最后一条结果集：旧版 UI 就是「只展示最后一个结果集」的语义。
            columns: last.columns,
            rows: last.rows,
            row_count: last.row_count,
            affected_rows: last.affected_rows
          };
        }
      }
    ]
  ]);
  async function handle(request) {
    const { method = "GET", pathname, headers = {}, body = null } = request ?? {};
    const route = routes.get(pathname);
    if (!route) {
      const error = engineError("NOT_FOUND", `\u672A\u77E5\u8DEF\u5F84\uFF1A${pathname}`);
      return { status: httpStatusForCode(error.code), body: fail(error) };
    }
    if (method !== route.method) {
      const error = engineError("METHOD_NOT_ALLOWED", `${pathname} \u53EA\u63A5\u53D7 ${route.method}`);
      return { status: httpStatusForCode(error.code), body: fail(error) };
    }
    try {
      if (route.auth) auth.verify(headers);
      const data = await route.handler({ body, headers, pool });
      return { status: 200, body: ok(data) };
    } catch (error) {
      const normalized = normalizeThrown(error);
      return { status: httpStatusForCode(normalized.code), body: fail(normalized) };
    }
  }
  return { handle, routes };
}

// service/src/http-server.mjs
var HOST = "127.0.0.1";
var SECRET_KEY_ENV = "ASTRAVIA_SERVICE_SECRET_ENGINE_KEY";
function emit(event, payload = {}) {
  process.stdout.write(
    `${JSON.stringify({ event, version: ENGINE_VERSION, ts: (/* @__PURE__ */ new Date()).toISOString(), ...payload })}
`
  );
}
function parseArgs(argv) {
  const args = { port: 0, dataDir: null, authDisabled: false, help: false };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--port") args.port = Number(argv[index += 1]);
    else if (token === "--data") args.dataDir = argv[index += 1] ?? null;
    else if (token === "--auth-disabled") args.authDisabled = true;
    else if (token === "--help" || token === "-h") args.help = true;
  }
  return args;
}
function digest(value) {
  return createHash2("sha256").update(value).digest();
}
function createAuth({ token, disabled = false } = {}) {
  const enabled = !disabled && typeof token === "string" && token.length > 0;
  const expected = enabled ? digest(token) : null;
  return {
    enabled,
    verify(headers = {}) {
      if (!enabled) return;
      const header = headers.authorization ?? headers.Authorization ?? "";
      const bearer = /^bearer\s+(.+)$/i.exec(String(header));
      const presented = bearer ? bearer[1].trim() : String(headers["x-dbx-token"] ?? "").trim();
      if (!presented || !timingSafeEqual(digest(presented), expected)) {
        throw engineError("UNAUTHORIZED", "\u7F3A\u5C11\u6216\u65E0\u6548\u7684\u5F15\u64CE\u8BBF\u95EE\u4EE4\u724C");
      }
    }
  };
}
function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    let failed = false;
    req.on("data", (chunk) => {
      if (failed) return;
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        failed = true;
        reject(engineError("PAYLOAD_TOO_LARGE", `\u8BF7\u6C42\u4F53\u8D85\u8FC7 ${MAX_BODY_BYTES} \u5B57\u8282`));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (failed) return;
      const raw = Buffer.concat(chunks).toString("utf8").trim();
      if (raw.length === 0) return resolve(null);
      try {
        resolve(JSON.parse(raw));
      } catch (error) {
        reject(engineError("BAD_REQUEST", `\u8BF7\u6C42\u4F53\u4E0D\u662F\u5408\u6CD5 JSON\uFF1A${error instanceof Error ? error.message : error}`));
      }
    });
    req.on("error", (error) => {
      if (!failed) reject(engineError("BAD_REQUEST", error instanceof Error ? error.message : String(error)));
    });
  });
}
function createEngineServer({ token, dataDir = null, authDisabled = false, idleTtlMs } = {}) {
  const pool = new ConnectionPool(idleTtlMs ? { idleTtlMs } : {});
  const auth = createAuth({ token, disabled: authDisabled });
  const router = createRouter({ pool, auth });
  const server = createServer(async (req, res) => {
    const send = (status, body) => {
      if (res.writableEnded) return;
      const payload = stringifyJson(body);
      res.writeHead(status, {
        "content-type": "application/json; charset=utf-8",
        "content-length": Buffer.byteLength(payload),
        "cache-control": "no-store"
      });
      res.end(payload);
    };
    let url;
    try {
      url = new URL(req.url ?? "/", `http://${HOST}`);
    } catch {
      const error = engineError("BAD_REQUEST", `\u975E\u6CD5\u8BF7\u6C42\u8DEF\u5F84\uFF1A${req.url}`);
      return send(400, { ok: false, error: { code: error.code, message: error.message } });
    }
    try {
      const body = req.method === "POST" ? await readJsonBody(req) : null;
      const outcome = await router.handle({
        method: req.method,
        pathname: url.pathname,
        headers: req.headers,
        body
      });
      send(outcome.status, outcome.body);
    } catch (error) {
      const code = error?.code ?? "INTERNAL";
      const status = code === "PAYLOAD_TOO_LARGE" ? 413 : code === "BAD_REQUEST" ? 400 : 500;
      emit("request-error", { path: url.pathname, code });
      send(status, { ok: false, error: { code, message: error?.message ?? String(error) } });
    }
  });
  server.on("clientError", (error, socket) => {
    emit("request-error", { path: null, code: "CLIENT_ERROR", message: error.message });
    if (socket.writable) socket.end("HTTP/1.1 400 Bad Request\r\n\r\n");
  });
  const reaper = setInterval(() => {
    pool.reap().catch(() => {
    });
  }, 6e4);
  reaper.unref?.();
  return { server, pool, auth, router, dataDir, reaper };
}
async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    process.stdout.write(
      "dbx-pro engine\n  --port <n>        listen port (0 = random)\n  --data <dir>      service data directory\n  --auth-disabled   disable token auth (local dev only)\n"
    );
    return;
  }
  if (!Number.isInteger(args.port) || args.port < 0 || args.port > 65535) {
    emit("server-error", { code: "BAD_PORT", message: `\u975E\u6CD5\u7AEF\u53E3\uFF1A${args.port}` });
    process.exit(1);
  }
  const token = process.env[SECRET_KEY_ENV];
  if (typeof token !== "string" || token.length === 0) {
    if (!args.authDisabled) {
      emit("server-error", {
        code: "NO_SECRET",
        message: `\u7F3A\u5C11\u5F15\u64CE\u8BBF\u95EE\u4EE4\u724C\uFF08\u73AF\u5883\u53D8\u91CF ${SECRET_KEY_ENV} \u672A\u8BBE\u7F6E\u6216\u4E3A\u7A7A\uFF09\uFF1B\u672C\u5730\u8C03\u8BD5\u8BF7\u663E\u5F0F\u4F20 --auth-disabled`
      });
      process.exit(1);
    }
  }
  const { server, pool, auth, reaper } = createEngineServer({
    token,
    dataDir: args.dataDir,
    authDisabled: args.authDisabled
  });
  if (!auth.enabled) emit("auth-disabled", { reason: args.authDisabled ? "flag" : "no-secret" });
  await new Promise((resolve) => {
    server.on("error", (error) => {
      emit("server-error", { code: error.code ?? "SERVER_ERROR", message: error.message });
      process.exit(1);
    });
    server.listen(args.port, HOST, () => resolve());
  });
  const address = server.address();
  emit("listening", {
    host: HOST,
    port: typeof address === "object" && address ? address.port : args.port,
    pid: process.pid,
    node: process.version,
    protocol: PROTOCOL_VERSION,
    auth: auth.enabled ? "enabled" : "disabled",
    dataDir: args.dataDir
  });
  let closing = false;
  const shutdown = async (signal) => {
    if (closing) return;
    closing = true;
    clearInterval(reaper);
    await new Promise((resolve) => server.close(() => resolve()));
    try {
      await pool.closeAll();
    } catch {
    }
    emit("shutdown", { signal });
    process.exit(0);
  };
  process.on("SIGTERM", () => void shutdown("SIGTERM"));
  process.on("SIGINT", () => void shutdown("SIGINT"));
}
main();
export {
  createAuth,
  createEngineServer
};
